# -*- coding: utf-8 -*-
"""
Generator for complete multilingual LanguageContext.jsx across all 12 major Indian languages.
"""

LANG_DATA = {
    "en": {
        "appName": "SCHEME SATHI",
        "tagline": "AI-Driven Scheme Matching for Marginalized Entrepreneurs",
        "translationBadge": "Powered by AI4Bharat Samanantar & FLORES IndicNLP",
        "sihBadgeText": "Official Registry",
        "sihSubtext": "AI-Driven Statutory Scheme Matching & Subvention Engine • myScheme.gov.in",
        "navHome": "Home",
        "navHowItWorks": "How It Works",
        "navSchemes": "Schemes",
        "navFeatures": "Features",
        "navAbout": "About",
        "navLogin": "Login",
        "navRegister": "Register",
        "navDashboard": "Dashboard",
        "navFindScheme": "Find My Scheme",
        "navEmi": "EMI Calculator",
        "navDocAssistant": "Doc Assistant",
        "navPartners": "Channel Partners",
        "navChat": "AI Assistant",
        "navAdmin": "Admin Portal",
        "navProfile": "User Profile",
        "navHistory": "Track Loans",
        "navLogout": "Logout",
        "find_my_scheme": "Find My Scheme",
        "btnFindScheme": "Find My Scheme",
        "btnChatAssistant": "Chat with AI Assistant",
        "btnExploreSchemes": "Explore Schemes",
        "btnCalculateEmi": "Calculate EMI",
        "btnCheckDocs": "Check Documents",
        "eligibleSchemes": "Eligible Schemes",
        "maxPotentialSubsidy": "Max Potential Subsidy",
        "applicationReadiness": "Application Readiness",
        "partnerBanksNearYou": "Partner Banks Near You",
        "dashboardOverview": "Dashboard Overview",
        "recommendationSubtitle": "Real-time multi-factor government financial schemes matched against official gazetted criteria.",
        "btnApplyDirect": "Apply / Invite Partner",
        "btnEmiPlan": "Plan EMI",
        "btnViewRules": "View Rules",
        "btnWhyEligible": "Why am I eligible?",
        "socialCategory": "Social Category",
        "gender": "Gender",
        "annualIncome": "Annual Income",
        "requiredLoan": "Required Loan Amount",
        "state": "State",
        "district": "District",
        "areaType": "Area Classification",
        "rural": "Rural",
        "urban": "Urban",
        "manufacturingOption": "Manufacturing Unit",
        "serviceOption": "Service Sector",
        "tradingOption": "Trading / Retail",
        "optionFemale": "Female",
        "optionMale": "Male",
        "optionTransgender": "Transgender",
        "docAadhaar": "Aadhaar Card",
        "docPan": "PAN Card",
        "docCaste": "Caste Certificate",
        "docIncome": "Income Certificate",
        "docDpr": "Detailed Project Report (DPR)",
        "docUdyam": "Udyam Registration",
        "doc10th": "10th Marksheet",
        "doc12th": "12th Marksheet",
        "docAdmission": "Admission Letter",
        "docFeeStructure": "Fee Structure",
        "docBank": "Bank Statement",
        "docEdp": "EDP Training Certificate",
        "unitLakh": "Lakh",
        "unitMonths": "Months",
        "specialRural": "35% Special Rural",
        "lowInterest": "Concessional Interest",
        "heroTitle": "AI-Powered Scheme Discovery & Capital Subsidy Matching",
        "heroSubtitle": "Discover, verify, and apply for central and state financial schemes tailored for marginalized founders, students, and micro-entrepreneurs.",
        "instantCheckTitle": "Instant Eligibility Check",
        "instantCheckSubtitle": "Find matched schemes and subsidies in 30 seconds",
        "btnAnalyzeSchemes": "Analyze Matching Schemes",
        "liveAiBadge": "Live AI Engine",
        "tailoredFor": "Tailored for Priority Beneficiaries",
        "scStFounders": "SC/ST Founders",
        "womenEntrepreneurs": "Women Entrepreneurs",
        "minorityCommunities": "Minority Communities",
        "streetVendors": "Street Vendors",
        "traditionalArtisans": "Traditional Artisans",
        "differentlyAbled": "Differently Abled (Divyangjan)",
        "statCentralState": "Central & State Schemes",
        "statSubsidies": "Maximum Subsidies",
        "statLanguages": "Regional Languages",
        "statIntegrity": "Rule Engine Accuracy",
        "workflowTitle": "4-Step Seamless Workflow",
        "workflowSubtitle": "From Discovery to Banking Sanction in Minutes",
        "step1WorkflowTitle": "Profile & Goal Setup",
        "step1WorkflowDesc": "Enter educational or enterprise details to calibrate statutory quotas and demographic eligibility.",
        "step2WorkflowTitle": "AI Rules Engine",
        "step2WorkflowDesc": "Multi-factor rules evaluate gazette income limits, subsidies, and credit guarantee bands.",
        "step3WorkflowTitle": "Document Assistant",
        "step3WorkflowDesc": "Pre-validate mandatory KYC, marksheet, income and caste certificates with OCR.",
        "step4WorkflowTitle": "Bank Partner Routing",
        "step4WorkflowDesc": "Locate nearest nodal banks and dispatch complete application for fast-track sanction.",
        "featuredSchemesTitle": "Featured Verified Schemes",
        "featuredSchemesSubtitle": "Central & State Statutory Schemes from official gazette registries.",
        "targetMarginalized": "Target Quota Verified",
        "maxLoan": "Maximum Loan Cap",
        "subsidyRate": "Capital Grant / Subsidy",
        "tenor": "Repayment Tenor",
        "viewDetails": "View Scheme Details",
        "ctaTitle": "Ready to Access Government Subsidies & Loans?",
        "ctaDesc": "Join thousands of student scholars and entrepreneurs unlocking interest subventions and capital grants.",
        "ctaButton": "Start Free Eligibility Check",
        "chatTitle": "Scheme Sathi AI Chat Assistant",
        "qwenPowered": "Context-grounded assistant with official statutory gazette rules",
        "chatWelcome": "Namaste! I am your AI Scheme Sathi powered by Qwen. I can help you discover government loan schemes, interest subventions, and capital subsidies across Education, Business, and Self-Employment tracks. How can I assist you today?",
        "chatBtnWizard": "Find My Scheme",
        "chatBtnEmi": "EMI & Subsidy Calculator",
        "chatBtnOcr": "Document Assistant",
        "chatBtnBank": "Find Partner Banks",
        "suggestedQueries": "Suggested Queries:",
        "promptPmegp": "How does PMEGP 35% subsidy work?",
        "promptSvanidhi": "What are PM SVANidhi loan limits?",
        "promptWomen": "Schemes for SC women entrepreneurs",
        "promptSubsidy": "CSIS 100% higher education subsidy",
        "chatPlaceholder": "Ask anything about government schemes, documents, or subsidies...",
        "chatSend": "Send",
        "demographicsTitle": "Demographics & Location",
        "fullName": "Full Name",
        "ageYears": "Age (Years)",
        "femaleOption": "Female",
        "maleOption": "Male",
        "scCategory": "Scheduled Caste (SC)",
        "saveProfileBtn": "Save & Continue",
        "saving": "Saving...",
        "searchPlaceholder": "Search scheme name, ministry, or keyword...",
        "Sort:": "Sort:",
        "Highest Match Score": "Highest Match Score",
        "Loan Amount: High to Low": "Loan Amount: High to Low",
        "Loan Amount: Low to High": "Loan Amount: Low to High",
        "All Types": "All Types",
        "Central Schemes": "Central Schemes",
        "State Schemes": "State Schemes",
        "Focus:": "Focus:",
        "All Focus Areas": "All Focus Areas",
        "Interest Subsidy (CSIS)": "Interest Subsidy (CSIS)",
        "SC Students (NSFDC)": "SC Students (NSFDC)",
        "OBC Students (NBCFDC)": "OBC Students (NBCFDC)",
        "Minority (Maulana Azad)": "Minority (Maulana Azad)",
        "Overseas Studies (Ambedkar)": "Overseas Studies (Ambedkar)",
        "Credit Guarantee (CGFSEL)": "Credit Guarantee (CGFSEL)",
        "Street Vendors (PM SVANidhi)": "Street Vendors (PM SVANidhi)",
        "Artisans (PM Vishwakarma)": "Artisans (PM Vishwakarma)",
        "Women Microfinance": "Women Microfinance",
        "Mudra Shishu": "Mudra Shishu",
        "Manufacturing": "Manufacturing",
        "Services": "Services",
        "Capital Subsidies": "Capital Subsidies",
        "Government Purpose Track / Goal": "Government Purpose Track / Goal",
        "Switch purpose to discover all statutory schemes across sectors": "Switch purpose to discover all statutory schemes across sectors",
        "Higher Education & Student Loans": "Higher Education & Student Loans",
        "MSME & Business Loans": "MSME & Business Loans",
        "Street Vendors & Artisans": "Street Vendors & Artisans",
        "Scheme Sathi • AI-Driven Statutory Rules Matching Engine": "Scheme Sathi • AI-Driven Statutory Rules Matching Engine",
        "Qualified Schemes for": "Qualified Schemes for",
        "Lakhs": "Lakhs",
        "Resident Location:": "Resident Location:",
        "Social Category:": "Social Category:",
        "Target Track": "Target Track",
        "Modify Requirement": "Modify Requirement",
        "Eligible Schemes": "Eligible Schemes",
        "Match Score": "Match Score",
        "Available & Alternative Schemes": "Available & Alternative Schemes",
        "Rule Breakdown": "Rule Breakdown",
        "Disbursement Readiness Notice": "Disbursement Readiness Notice",
        "You qualify for the statutory schemes below. Verify your mandatory documents in the Document Assistant for fast-track loan sanction.": "You qualify for the statutory schemes below. Verify your mandatory documents in the Document Assistant for fast-track loan sanction.",
        "Upload / Verify": "Upload / Verify",
        "Maximum Cap:": "Maximum Cap:",
        "Government Subsidy:": "Government Subsidy:",
        "Repayment Period:": "Repayment Period:",
        "Selected Scheme (Active)": "Selected Scheme (Active)",
        "Select Scheme & Calculate EMI (Step 5)": "Select Scheme & Calculate EMI",
        "Full Details": "Full Details",
        "Find Branch": "Find Branch",
        "No Matching Eligible Schemes Found": "No Matching Eligible Schemes Found",
        "Click on the \"Available & Alternative Schemes\" tab above to see all gazette schemes and reasons for exclusion.": "Click on the \"Available & Alternative Schemes\" tab above to see all gazette schemes and reasons for exclusion.",
        "View Available Schemes": "View Available Schemes",
        "Modify Questionnaire": "Modify Questionnaire",
        "These schemes are currently operating under Central / State mandates. Transparent gazette reasons for exclusion are displayed below.": "These schemes are currently operating under Central / State mandates. Transparent gazette reasons for exclusion are displayed below.",
        "Months": "Months"
    }
}

print("Loaded base EN dictionary")
