# -*- coding: utf-8 -*-
"""
Full Multilingual Scheme Sathi Builder (All 11 Languages + English)
"""
import os
import json

# 1. Generate full DICTIONARY with 12 languages
from generate_master_multilingual_app import LANGUAGES, SCHEME_MAP

# Load base dictionaries
base_en = {
    "navHome": "Home", "navFindScheme": "Find My Scheme", "navSchemes": "All Schemes",
    "navEmi": "EMI & Subsidy", "navDocAssistant": "Document OCR", "navPartners": "Bank Locator",
    "navChat": "AI Assistant", "navDashboard": "Dashboard", "navAdmin": "Admin",
    "navLogin": "Login", "navRegister": "Register", "navLogout": "Logout", "selectLanguage": "Select Language",
    "sihBadgeText": "Smart India Hackathon 2026", "sihSubtext": "Problem Statement SIH26092 • Ministry of MSME / Financial Services",
    "translationBadge": "11 Indian Languages (AI4Bharat Samanantar)", "liveAiBadge": "Deterministic Rule Engine",
    "targetMarginalized": "Marginalized", "unitMonths": "Months", "unitLakh": "Lakh", "unitCrore": "Cr",
    "lowInterest": "Low Interest Subsidy", "bankGuarantee": "Bank Guarantee", "specialRural": "Up to 35% Special Rural",
    "sliderMinSVANidhi": "₹10,000 (SVANidhi)", "sliderMidMudra": "₹10 Lakh (Mudra)", "sliderMidPMEGP": "₹50 Lakh (PMEGP)", "sliderMaxStandUp": "₹10 Cr (StandUp)",
    "optionSC": "Scheduled Caste (SC)", "optionST": "Scheduled Tribe (ST)", "optionOBC": "Other Backward Class (OBC)", "optionMinority": "Minority Community", "optionGeneral": "General Category",
    "optionFemale": "Woman / Female", "optionMale": "Male", "optionTransgender": "Transgender",
    "optionGraduate": "Graduate / Degree Holder", "option12th": "12th Standard Pass", "option8th": "8th Standard Pass (PMEGP Eligible for >₹10L)", "optionBelow8th": "Below 8th Standard",
    "optionRural": "Rural (Higher Subsidy up to 35%)", "optionUrban": "Urban (Subsidy up to 25%)",
    "optionNewStage": "New Enterprise (Greenfield Project)", "optionExpansionStage": "Expansion of Existing Unit",
    "manufacturingOption": "Manufacturing Industry", "serviceOption": "Service Sector Enterprise", "tradingOption": "Trading & Retail Business",
    "streetVendorOption": "Street Vendor / Hawkers", "artisanOption": "Traditional Artisan / Craftsman",
    "heroTitle": "Empowering Marginalized Entrepreneurs with Verified Govt Schemes",
    "heroSubtitle": "A deterministic rule engine that evaluates statutory Central and State loan schemes, affirmative subsidy slabs, and demographic quotas in 11 Indian languages with 0% hallucinations.",
    "btnFindScheme": "Find Eligible Schemes", "btnChatAssistant": "Ask AI Scheme Assistant", "tailoredFor": "Dedicated Focus Groups",
    "scStFounders": "SC / ST Founders", "womenEntrepreneurs": "Women Entrepreneurs", "minorityCommunities": "Minority Communities",
    "streetVendors": "Street Vendors", "traditionalArtisans": "Traditional Artisans", "differentlyAbled": "Differently Abled (PwD)",
    "instantCheckTitle": "Instant Scheme Eligibility Check", "instantCheckSubtitle": "Discover capital subsidies & loan limits in 30 seconds",
    "socialCategory": "Social Category", "gender": "Gender", "businessType": "Business Activity", "requiredLoan": "Required Loan Amount",
    "btnAnalyzeSchemes": "Analyze My Eligibility", "statCentralState": "Central & State Schemes", "statSubsidies": "Capital Subsidies Available",
    "statLanguages": "Regional Languages Supported", "statIntegrity": "Gazette Rule Accuracy",
    "workflowTitle": "How Scheme Sathi Works", "workflowSubtitle": "From Profile Input to Bank Sanction in 4 Transparent Steps",
    "step1WorkflowTitle": "Enter Business Profile", "step1WorkflowDesc": "Tell us your social category, location, proposed project cost, and education.",
    "step2WorkflowTitle": "Rule Engine Evaluation", "step2WorkflowDesc": "Deterministic logic checks statutory criteria without LLM hallucinations.",
    "step3WorkflowTitle": "Subsidy & EMI Simulation", "step3WorkflowDesc": "Calculate net monthly repayment after upfront capital subsidies.",
    "step4WorkflowTitle": "Locate Partner Bank", "step4WorkflowDesc": "Connect directly with nodal branches and CSC centers for loan sanction.",
    "featuredSchemesTitle": "Flagship Government Loan Schemes", "featuredSchemesSubtitle": "Verified Central & State assistance programs for marginalized entrepreneurs",
    "btnExploreSchemes": "View All Schemes", "maxLoan": "Max Loan", "subsidyRate": "Subsidy", "tenor": "Repayment Tenor", "viewDetails": "View Full Details",
    "ctaTitle": "Ready to Launch or Expand Your Enterprise?", "ctaDesc": "Check your eligibility across 25+ Central & State schemes with 100% gazette accuracy.", "ctaButton": "Start 5-Step Evaluation",
    "wizardTitle": "Scheme Eligibility & Subsidy Evaluation Wizard", "wizardSubtitle": "5-Step deterministic assessment tailored for marginalized entrepreneurs and students",
    "step1Title": "Demographics", "step1Desc": "Social identity, age, and affirmative action category",
    "step2Title": "Location", "step2Desc": "State, district, and rural/urban area classification",
    "step3Title": "Enterprise", "step3Desc": "Industry sector, stage, and special artisan skills",
    "step4Title": "Financials", "step4Desc": "Project cost, required loan amount, and margin money",
    "step5Title": "Documents", "step5Desc": "Readiness checklist for bank loan sanction",
    "socialCategoryLabel": "Social Category (Affirmative Action)", "genderLabel": "Gender", "ageLabel": "Age (Years)",
    "educationLabel": "Highest Educational Qualification", "differentlyAbledLabel": "Differently Abled (PwD / Divyangjan)",
    "stateLabel": "State / UT", "districtLabel": "District", "areaTypeLabel": "Area Classification (Rural vs Urban)", "pincodeLabel": "Pincode",
    "ruralOption": "Rural Area (Higher Subsidy up to 35%)", "urbanOption": "Urban Area (Subsidy up to 25%)",
    "businessStageLabel": "Business Stage", "hasTrainingLabel": "Completed EDP or Skill Development Training (+15% score)",
    "isArtisanLabel": "Engaged in Traditional Artisan / Craft Trade (PM Vishwakarma)", "isVendorLabel": "Street Food / Urban Hawker (PM SVANidhi)",
    "requiredLoanLabel": "Required Loan Amount", "projectCostLabel": "Total Estimated Project Cost (₹)",
    "ownContributionLabel": "Promoter Contribution / Margin Money (₹)", "pmegpMarginNote": "Special Category requires only 5% margin money under PMEGP.",
    "hasAadhaarLabel": "Aadhaar Card with Mobile Link", "hasPanLabel": "Permanent Account Number (PAN)",
    "hasCasteLabel": "Caste / Category Certificate", "hasDprLabel": "Detailed Project Report (DPR)",
    "hasBankLabel": "Active Bank Account", "hasUdyamLabel": "Udyam MSME Registration",
    "btnPrevious": "Back", "btnNext": "Continue", "btnEvaluateSchemes": "Evaluate Eligible Schemes", "evaluatingText": "Evaluating Gazette Rules...",
    "resultsTitle": "Schemes Matched", "resultsSubtitle": "Evaluated against statutory Central & State gazette criteria and affirmative subsidy slabs.",
    "btnRecalculate": "Recalculate Profile", "mySchemePortal": "myScheme.gov.in Portal", "searchPlaceholder": "Search scheme name, ministry, or keyword...",
    "filterAll": "All Schemes", "filterCentral": "Central Schemes", "filterState": "State Schemes",
    "sortByScore": "Match Score (High to Low)", "sortByLoanDesc": "Max Loan Amount (High to Low)", "sortByLoanAsc": "Max Loan Amount (Low to High)",
    "schemeMatchScore": "Match Score", "cardMaxLoan": "Maximum Loan Limit", "cardSubsidy": "Capital Subsidy",
    "cardTenor": "Repayment Tenor", "cardMarginMoney": "Required Margin Money", "cardMoratorium": "Moratorium Period",
    "btnApplyOnline": "Apply Online", "btnViewDetails": "Scheme Guidelines", "btnWhyEligible": "Why Am I Eligible?",
    "ineligibleHeading": "Ineligible Schemes & Statutory Reasons", "ineligibleSubtitle": "Schemes where requirements were not met based on gazetted criteria",
    "reasonHeading": "Reason for Ineligibility", "positiveFactors": "Positive Eligibility Factors", "limitingFactors": "Risk & Limiting Factors",
    "noSchemesFound": "No schemes matched your exact profile. Please adjust your loan amount or parameters.", "locateBankPartner": "Locate Nearest Partner Bank",
    "chatTitle": "AI Scheme Sathi Assistant", "chatSubtitle": "Powered by Qwen (Local LLM via Ollama) and Samanantar IndicNLP",
    "chatPlaceholder": "Ask about PMEGP subsidy, Mudra loans, SVANidhi, documents...", "chatSend": "Send",
    "qwenPowered": "Official myScheme.gov.in Gazette Data & Local Qwen LLM", "suggestedQueries": "Suggested Queries:",
    "promptPmegp": "How much subsidy will I get under PMEGP in a rural area?", "promptSvanidhi": "Can street vendors get collateral-free loan under SVANidhi?",
    "promptWomen": "What are the special loan schemes for women entrepreneurs?", "promptSubsidy": "What documents are required for capital subsidy?",
    "chatWelcome": "Namaste! I am your AI Scheme Sathi powered by Qwen and Samanantar IndicNLP. I provide factual, gazetted guidance on 25+ Central and State government loan schemes, capital subsidies, and document checklists. How can I help you today?",
    "chatBtnWizard": "🚀 5-Step Scheme Match Wizard", "chatBtnEmi": "📊 EMI & Subsidy Simulator",
    "chatBtnOcr": "📑 OCR Document Verification", "chatBtnBank": "📍 Nearest Partner Bank Locator",
    "calcTitle": "Government Scheme EMI & Subsidy Calculator", "calcSubtitle": "Calculate monthly EMI after deducting Central/State capital subsidies (e.g. 35% PMEGP).",
    "calcQuickPresets": "Quick Presets:", "loanAmountLabel": "Sanctioned Loan Amount", "interestRateLabel": "Annual Interest Rate (%)",
    "tenureYearsLabel": "Repayment Tenor (Years)", "subsidyPercentLabel": "Capital Subsidy Rate (%)", "moratoriumMonthsLabel": "Moratorium Period (Months)",
    "effectiveSubsidy": "Upfront Capital Subsidy", "netPrincipal": "Net Loan Principal Payable", "monthlyEmi": "Estimated Monthly EMI",
    "totalInterest": "Total Interest Payable", "totalPayment": "Total Amount Payable", "amortizationSchedule": "Year-wise Loan Amortization Schedule",
    "yearCol": "Year", "principalPaidCol": "Principal Paid", "interestPaidCol": "Interest Paid", "balanceCol": "Remaining Balance",
    "docAssistantTitle": "AI Document Assistant & OCR Verification", "docAssistantSubtitle": "Extract data and cross-verify identity details against profile to eliminate bank rejection.",
    "docSelectCategory": "Select Document Category", "uploadFileBtn": "Choose Document File", "verifyOcrBtn": "Run OCR Verification",
    "verificationPassed": "Verification Passed (100% Match)", "verificationPending": "Verification Pending", "extractedDataHeading": "OCR Extracted Certificate Fields",
    "docChecklistTitle": "Master Document Checklist", "docChecklistSubtitle": "Status of required certificates for bank loan sanction",
    "btnPrintChecklist": "Print Checklist", "mandatoryTag": "Mandatory", "optionalTag": "Optional",
    "docAadhaar": "Aadhaar Card (UIDAI ID)", "docCaste": "Caste / Community Certificate", "docPan": "PAN Card (Income Tax Dept)",
    "docIncome": "Income Certificate (Tahsildar Issued)", "docDpr": "Detailed Project Report (DPR)", "docUdyam": "Udyam MSME Registration Certificate",
    "docBank": "Bank Passbook / 6M Statement", "docEdp": "EDP / Skill Training Certificate",
    "partnerTitle": "Partner Bank & CSC Service Points", "partnerSubtitle": "Ranks nearby financial institutions by physical distance (km) and scheme sanction authority.",
    "filterCity": "Select City", "filterSchemePartner": "Filter by Scheme", "allCities": "All Cities", "allSchemePartners": "All Scheme Partners",
    "btnBookAppointment": "Book Bank Appointment", "appointmentSuccess": "Appointment Request Submitted Successfully!",
    "welcomeUser": "Welcome back", "dashboardSubtitle": "Beneficiary Dashboard • SIH26092", "kpiEligibleSchemes": "Eligible Schemes",
    "kpiRuleVerified": "100% Rule Verified", "kpiMaxSubsidy": "Max Potential Subsidy", "kpiReadinessScore": "Application Readiness Score",
    "kpiNearestBank": "Nearest Nodal Branch", "btnUpdateProfile": "Update Profile", "recentMatches": "Top Matched Schemes"
}

# Import or build localized dictionaries for hi, ta, te, kn, ml, mr, bn, gu, pa, or, as
with open("backend/app/services/indic_translation.py", "r", encoding="utf-8") as f:
    backend_content = f.read()

print("Loaded base dictionary. Generating comprehensive 11-language front-end context...")
