import React, { createContext, useContext, useState, useEffect } from 'react';
import axios from 'axios';

const LanguageContext = createContext();

export const LANGUAGES = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'or', name: 'Odia', native: 'ଓଡ଼ିଆ' },
  { code: 'as', name: 'Assamese', native: 'অসমীয়া' }
];

export const SCHEME_MAP = {
  PMEGP: {
    hi: { name: "प्रधानमंत्री रोजगार सृजन कार्यक्रम (PMEGP)", desc: "विनिर्माण व सेवा क्षेत्र में सूक्ष्म उद्यमों के लिए 35% तक पूंजीगत सब्सिडी सहित ऋण योजना।" },
    ta: { name: "பிரதமரின் வேலைவாய்ப்பு உருவாக்கும் திட்டம் (PMEGP)", desc: "உற்பத்தி மற்றும் சேவைத் துறைகளில் சுயதொழில் தொடங்க 35% வரை மானியம் வழங்கும் கடன் திட்டம்." },
    te: { name: "ప్రధాన మంత్రి ఉపాధి కల్పన కార్యక్రమం (PMEGP)", desc: "ఉత్పాదక మరియు సేవా రంగాల్లో సూక్ష్మ పరిశ్రమల స్థాపనకు 35% వరకు సబ్సిడీతో కూడిన రుణ పథకం." },
    kn: { name: "ಪ್ರಧಾನ ಮಂತ್ರಿ ಉದ್ಯೋಗ ಸೃಷ್ಟಿ ಕಾರ್ಯಕ್ರಮ (PMEGP)", desc: "ಉತ್ಪಾದನಾ ಮತ್ತು ಸೇವಾ ವಲಯಗಳಲ್ಲಿ ಉದ್ಯಮ ಸ್ಥಾಪಿಸಲು ಶೇ.35 ರವರೆಗೆ ಸಬ್ಸಿಡಿ ನೀಡುವ ಯೋಜನೆ." },
    ml: { name: "പ്രധാനമന്ത്രി തൊഴിൽ സൃഷ്ടി പദ്ധതി (PMEGP)", desc: "ഉൽപ്പാദന, സേവന മേഖലകളിൽ സംരംഭങ്ങൾ തുടങ്ങാൻ 35% വരെ സബ്‌സിഡി നൽകുന്ന വായ്പാ പദ്ധതി." },
    mr: { name: "पंतप्रधान रोजगार निर्मिती कार्यक्रम (PMEGP)", desc: "उत्पादन व सेवा क्षेत्रात सूक्ष्म उद्योग सुरू करण्यासाठी ३५% पर्यंत भांडवली अनुदान योजना." },
    bn: { name: "প্রধানমন্ত্রী কর্মসংস্থান সৃষ্টি প্রকল্প (PMEGP)", desc: "উৎপাদন ও সেবা ক্ষেত্রে ক্ষুদ্র উদ্যোগ স্থাপনের জন্য ৩৫% পর্যন্ত মূলধন ভর্তুকিযুক্ত ঋণ প্রকল্প।" },
    gu: { name: "પ્રધાનમંત્રી રોજગાર નિર્માણ કાર્યક્રમ (PMEGP)", desc: "ઉત્પાદન અને સેવા ક્ષેત્રે સૂક્ષ્મ ઉદ્યોગો શરૂ કરવા માટે ૩૫% સુધીની સબસિડી સાથેની યોજના." },
    pa: { name: "ਪ੍ਰਧਾਨ ਮੰਤਰੀ ਰੋਜ਼ਗਾਰ ਉਤਪਤੀ ਪ੍ਰੋਗਰਾਮ (PMEGP)", desc: "ਨਿਰਮਾਣ ਅਤੇ ਸੇਵਾ ਖੇਤਰਾਂ ਵਿੱਚ ਸਵੈ-ਰੋਜ਼ਗਾਰ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ੩੫% ਤੱਕ ਸਬਸਿਡੀ ਵਾਲੀ ਕਰਜ਼ਾ ਯੋਜਨਾ।" },
    or: { name: "ପ୍ରଧାନମନ୍ତ୍ରୀ ରୋଜଗାର ସୃଷ୍ଟି କାର୍ଯ୍ୟକ୍ରମ (PMEGP)", desc: "ଉତ୍ପାଦନ ଓ ସେବା କ୍ଷେତ୍ରରେ କ୍ଷୁଦ୍ର ଉଦ୍ୟୋଗ ସ୍ଥାପନ ପାଇଁ ୩୫% ପର୍ଯ୍ୟନ୍ତ ରିହାତିଯୁକ୍ତ ଋଣ ଯୋଜନା।" },
    as: { name: "প্ৰধানমন্ত্ৰী নিয়োগ সৃষ্টি কাৰ্যসূচী (PMEGP)", desc: "উৎপাদন আৰু সেৱা খণ্ডত উদ্যোগ স্থাপনৰ বাবে ৩৫% লৈকে ৰাজসাহায্যযুক্ত ঋণ আঁচনি।" }
  },
  CSIS: {
    hi: { name: "केंद्रीय क्षेत्र ब्याज सब्सिडी योजना (CSIS)", desc: "व्यावसायिक व तकनीकी उच्च शिक्षा के लिए अध्ययन अवधि व 1 वर्ष के अधिस्थगन तक 100% ब्याज छूट।" },
    ta: { name: "மத்திய துறை வட்டி மானியத் திட்டம் (CSIS)", desc: "தொழில்முறை மற்றும் தொழில்நுட்ப உயர்கல்விக்கு படிப்புக் காலம் மற்றும் 1 ஆண்டு வரை 100% முழு வட்டி மானியம்." },
    te: { name: "కేంద్ర రంగ వడ్డీ రాయితీ పథకం (CSIS)", desc: "వృత్తిపరమైన ఉన్నత విద్య కోసం కోర్సు వ్యవధి మరియు 1 సంవత్సరం వరకు 100% పూర్తి వడ్డీ రాయితీ." },
    kn: { name: "ಕೇಂದ್ರ ವಲಯದ ಬಡ್ಡಿ ಸಬ್ಸಿಡಿ ಯೋಜನೆ (CSIS)", desc: "ವೃತ್ತಿಪರ ಉನ್ನತ ಶಿಕ್ಷಣಕ್ಕಾಗಿ ವ್ಯಾಸಂಗದ ಅವಧಿಯಲ್ಲಿ ಶೇ.100 ರಷ್ಟು ಪೂರ್ಣ ಬಡ್ಡಿ ರಿಯಾಯಿತಿ." },
    ml: { name: "കേന്ദ്ര പലിശ സബ്‌സിഡി പദ്ധതി (CSIS)", desc: "ഉന്നത വിദ്യാഭ്യാസ വായ്പകൾക്ക് പഠനകാലയളവിൽ 100% പലിശ ഇളവ്." },
    mr: { name: "केंद्रीय क्षेत्र व्याज सवलत योजना (CSIS)", desc: "तांत्रिक व व्यावसायिक उच्च शिक्षणासाठी १००% पूर्ण व्याज सवलत." },
    bn: { name: "কেন্দ্রীয় ক্ষেত্র সুদ ভর্তুকি প্রকল্প (CSIS)", desc: "উচ্চ শিক্ষার জন্য কোর্স চলাকালীন ১০০% সম্পূর্ণ সুদ মওকুফ।" },
    gu: { name: "સેન્ટ્રલ સેક્ટર વ્યાજ સબસિડી યોજના (CSIS)", desc: "ઉચ્ચ શિક્ષણ માટે અભ્યાસ સમયગાળા દરમિયાન ૧૦૦% વ્યાજ માફી." },
    pa: { name: "ਕੇਂਦਰੀ ਖੇਤਰ ਵਿਆਜ ਸਬਸਿਡੀ ਸਕੀਮ (CSIS)", desc: "ਉੱਚ ਸਿੱਖਿਆ ਲਈ ਪੜ੍ਹਾਈ ਦੌਰਾਨ ੧੦੦% ਮੁਕੰਮਲ ਵਿਆਜ ਛੋਟ।" },
    or: { name: "କେନ୍ଦ୍ରୀୟ କ୍ଷେତ୍ର ସୁଧ ରିହାତି ଯୋଜନା (CSIS)", desc: "ଉଚ୍ଚ ଶିକ୍ଷା ପାଇଁ ଅଧ୍ୟୟନ ସମୟରେ ୧୦୦% ସମ୍ପୂର୍ଣ୍ଣ ସୁଧ ରିହାତି।" },
    as: { name: "কেন্দ্ৰীয় খণ্ডৰ সুদ ৰাজসাহায্য আঁচনি (CSIS)", desc: "উচ্চ শিক্ষাৰ বাবে ১০০% সম্পূৰ্ণ সুদ ৰেহাই।" }
  },
  "STANDUP-IND": {
    hi: { name: "स्टैंड-अप इंडिया योजना (SC/ST व महिला उद्यमी)", desc: "अजा/अजजा और महिला उद्यमियों को नए व्यवसाय के लिए ₹10 लाख से ₹1 करोड़ तक का बैंक ऋण।" },
    ta: { name: "ஸ்டாண்ட்-அப் இந்தியா திட்டம் (SC/ST & பெண்கள்)", desc: "SC/ST மற்றும் பெண் தொழில்முனைவோருக்கு ₹10 இலட்சம் முதல் ₹1 கோடி வரை வங்கி கடன் வசதி." },
    te: { name: "స్టాండ్-అప్ ఇండియా పథకం (SC/ST & మహిళలు)", desc: "SC/ST మరియు మహిళా పారిశ్రామికవేత్తలకు ₹10 లక్షల నుండి ₹1 కోట్ల వరకు బ్యాంక్ రుణం." },
    kn: { name: "ಸ್ಟ್ಯಾಂಡ್‌-ಅಪ್ ಇಂಡಿಯಾ ಯೋಜನೆ (SC/ST & ಮಹಿಳೆಯರು)", desc: "SC/ST ಮತ್ತು ಮಹಿಳಾ ಉದ್ಯಮಿಗಳಿಗೆ ₹10 ಲಕ್ಷದಿಂದ ₹1 ಕೋಟಿವರೆಗೆ ಬ್ಯಾಂಕ್ ಸಾಲ ಸೌಲಭ್ಯ." },
    ml: { name: "സ്റ്റാൻഡ്-അപ്പ് ഇന്ത്യ പദ്ധതി (പട്ടികജാതി/പട്ടികവർഗ്ഗം & വനിതകൾ)", desc: "പട്ടികജാതി/പട്ടികവർഗ്ഗ, വനിതാ സംരംഭകർക്ക് ₹10 ലക്ഷം മുതൽ ₹1 കോടി വരെ ബാങ്ക് വായ്പ." },
    mr: { name: "स्टँड-अप इंडिया योजना (SC/ST व महिला)", desc: "नवीन उद्योगासाठी अनु.जाती/जमाती व महिलांना ₹१० लाख ते ₹१ कोटीपर्यंत बँक कर्ज सुविधा." },
    bn: { name: "স্ট্যান্ড-আপ ইন্ডিয়া প্রকল্প (SC/ST ও নারী)", desc: "তপশিলি জাতি/উপজাতি ও নারী উদ্যোক্তাদের জন্য ১০ লাখ থেকে ১ কোটি টাকা পর্যন্ত ব্যাংক ঋণ সুবিধা।" },
    gu: { name: "સ્ટેન્ડ-અપ ઇન્ડિયા યોજના (SC/ST અને મહિલાઓ)", desc: "નવા વ્યવસાય માટે SC/ST અને મહિલાઓને ₹૧૦ લાખથી ₹૧ કરોડ સુધીની બેંક લોન સહાય." },
    pa: { name: "ਸਟੈਂਡ-ਅੱਪ ਇੰਡੀਆ ਸਕੀਮ (SC/ST ਅਤੇ ਮਹਿਲਾਵਾਂ)", desc: "ਨਵਾਂ ਕਾਰੋਬਾਰ ਸ਼ੁਰੂ ਕਰਨ ਲਈ SC/ST ਅਤੇ ਮਹਿਲਾਵਾਂ ਨੂੰ ₹੧੦ ਲੱਖ ਤੋਂ ₹੧ ਕਰੋੜ ਤੱਕ ਬੈਂਕ ਕਰਜ਼ਾ।" },
    or: { name: "ଷ୍ଟାଣ୍ଡ-ଅପ ଇଣ୍ଡିଆ ଯୋଜନା (SC/ST ଓ ମହିଳା)", desc: "ନୂତନ ଉଦ୍ୟୋଗ ପାଇଁ SC/ST ଓ ମହିଳାମାନଙ୍କୁ ₹୧୦ ଲକ୍ଷରୁ ₹୧ କୋଟି ପର୍ଯ୍ୟନ୍ତ ବ୍ୟାଙ୍କ ଋଣ।" },
    as: { name: "ষ্টেণ্ড-আপ ইণ্ডিয়া আঁচনি (SC/ST আৰু মহিলা)", desc: "নতুন ব্যৱসায়ৰ বাবে SC/ST আৰু মহিলাসকলক ১০ লাখৰ পৰা ১ কোটি টকালৈকে বেংক ঋণ।" }
  },
  PM_SVANIDHI: {
    hi: { name: "पीएम स्ट्रीट वेंडर्स आत्मनिर्भर निधि (पीएम स्वनिधि)", desc: "स्ट्रीट वेंडरों को ₹10,000 से ₹50,000 तक बिना गारंटी कार्यशील पूंजी ऋण व 7% ब्याज छूट।" },
    ta: { name: "பிரதமரின் தெருவோர வியாபாரிகள் தற்சார்பு நிதி (PM ஸ்வநிதி)", desc: "தெருவோர வியாபாரிகளுக்கு பிணையற்ற ₹10,000 முதல் ₹50,000 வரை கடன் மற்றும் 7% வட்டி மானியம்." },
    te: { name: "పీఎం స్వనిధి పథకం (వీధి వ్యాపారుల ఆత్మనిర్భర్ నిధి)", desc: "వీధి వ్యాపారులకు ₹10,000 నుండి ₹50,000 వరకు పూచీకత్తు లేని రుణం మరియు 7% వడ్డీ రాయితీ." },
    kn: { name: "ಪ್ರಧಾನ ಮಂತ್ರಿ ಬೀದಿ ಬದಿ ವ್ಯಾಪಾರಿಗಳ ಆತ್ಮನಿರ್ಭರ ನಿಧಿ (ಪಿಎಂ ಸ್ವನಿಧಿ)", desc: "ಬೀದಿ ಬದಿ ವ್ಯಾಪಾರಿಗಳಿಗೆ ₹10,000 ದಿಂದ ₹50,000 ವರೆಗೆ ಖಾತರಿ ರಹಿತ ಸಾಲ ಮತ್ತು ಶೇ.7 ಬಡ್ಡಿ ರಿಯಾಯಿತಿ." },
    ml: { name: "പി.എം സ്വനിധി പദ്ധതി (തെരുവ് കച്ചവടക്കാർക്കായുള്ള വായ്പ)", desc: "തെരുവ് കച്ചവടക്കാർക്ക് ₹10,000 മുതൽ ₹50,000 വരെ ഈടില്ലാത്ത വായ്പയും 7% പലിശ ഇളവും." },
    mr: { name: "पीएम पथविक्रेते आत्मनिर्भर निधी (पीएम स्वनिधी)", desc: "फेरीवाल्यांना विनातारण ₹१०,००० ते ₹५०,००० पर्यंत कर्ज व ७% व्याज सवलत." },
    bn: { name: "প্রধানমন্ত্রী পিএম স্বনিধি প্রকল্প (পথ বিক্রেতাদের জন্য)", desc: "পথ বিক্রেতাদের জন্য জামিনমুক্ত ১০,০০০ থেকে ৫০,০০০ টাকা পর্যন্ত ঋণ ও ৭% সুদ ছাড়।" },
    gu: { name: "પીએમ સ્વનિધિ યોજના (શેરી ફેરિયાઓ માટે)", desc: "શેરી ફેરિયાઓ માટે તારણ મુક્ત ₹૧૦,૦૦૦ થી ₹૫૦,૦૦૦ સુધીની લોન અને ૭% વ્યાજ રાહત." },
    pa: { name: "ਪੀਐਮ ਸਵਨਿਧੀ ਸਕੀਮ (ਰੇਹੜੀ-ਫੜ੍ਹੀ ਵਾਲਿਆਂ ਲਈ)", desc: "ਰੇਹੜੀ ਵਾਲਿਆਂ ਲਈ ਬਿਨਾਂ ਗਰੰਟੀ ₹੧੦,੦੦੦ ਤੋਂ ₹੫੦,੦੦੦ ਕਰਜ਼ਾ ਅਤੇ ੭% ਵਿਆਜ ਛੋਟ।" },
    or: { name: "ପିଏମ ସ୍ୱନିଧି ଯୋଜନା (ରାସ୍ତାକଡ଼ ବିକ୍ରେତାଙ୍କ ପାଇଁ)", desc: "ରାସ୍ତାକଡ଼ ବିକ୍ରେତାଙ୍କ ପାଇଁ ବିନା ଜାମିନରେ ₹୧୦,୦୦୦ ରୁ ₹୫୦,୦୦୦ ଋଣ ଏବଂ ୭% ସୁଧ ରିହାତି।" },
    as: { name: "পিএম স্বনিধি আঁচনি (পথ বিক্ৰেতাসকলৰ বাবে)", desc: "পথ বিক্ৰেতাসকলৰ বাবে বন্ধকমুক্ত ১০,০০০ ৰ পৰা ৫০,০০০ টকা ঋণ আৰু ৭% সুদ ৰেহাই।" }
  },
  PM_VISHWAKARMA: {
    hi: { name: "पीएम विश्वकर्मा योजना (पारंपरिक कारीगर व शिल्पकार)", desc: "18 पारंपरिक व्यवसायों के शिल्पकारों को कौशल प्रशिक्षण, ₹15,000 टूलकिट व 5% ब्याज पर ₹3 लाख ऋण।" },
    ta: { name: "பிரதமரின் விஸ்வகர்மா திட்டம் (பாரம்பரிய கைவினைஞர்கள்)", desc: "18 பாரம்பரிய கைவினைஞர்களுக்கு பயிற்சி, ₹15,000 கருவி மானியம் மற்றும் 5% வட்டியில் ₹3 இலட்சம் கடன்." },
    te: { name: "పీఎం విశ్వకర్మ పథకం (సాంప్రదాయ కళాకారులు)", desc: "18 సాంప్రదాయ వృత్తుల వారికి శిక్షణ, ₹15,000 టూల్‌కిట్ మరియు 5% వడ్డీతో ₹3 లక్షల రుణం." },
    kn: { name: "ಪಿಎಂ ವಿಶ್ವಕರ್ಮ ಯೋಜನೆ (ಪಾರಂಪರಿಕ ಕುಶಲಕರ್ಮಿಗಳು)", desc: "18 ಪಾರಂಪರಿಕ ವೃತ್ತಿಗಳ ಕುಶಲಕರ್ಮಿಗಳಿಗೆ ತರಬೇತಿ, ₹15,000 ಟೂಲ್‌ಕಿಟ್ ಮತ್ತು ಶೇ.5 ಬಡ್ಡಿಯಲ್ಲಿ ₹3 ಲಕ್ಷ ಸಾಲ." },
    ml: { name: "പി.എം വിശ്വകർമ്മ പദ്ധതി (കരകൗശല വിദഗ്ദ്ധർ)", desc: "18 പരമ്പരാഗത തൊഴിലുകൾക്ക് പരിശീലനം, ₹15,000 ടൂൾകിറ്റ്, 5% പലിശയിൽ ₹3 ലക്ഷം വായ്പ." },
    mr: { name: "पीएम विश्वकर्मा योजना (पारंपरिक कारागीर व शिल्पकार)", desc: "१८ पारंपरिक कारागिरांना कौशल्य प्रशिक्षण, ₹१५,००० टूलकिट व ५% व्याजाने ₹३ लाख कर्ज." },
    bn: { name: "প্রধানমন্ত্রী বিশ্বকর্মা প্রকল্প (ঐতিহ্যবাহী কারিগর ও শিল্পী)", desc: "১৮টি ঐতিহ্যবাহী পেশার কারিগরদের জন্য প্রশিক্ষণ, ১৫,০০০ টাকা টুলকিট ও ৫% সুদে ৩ লাখ টাকা ঋণ।" },
    gu: { name: "પીએમ વિશ્વકર્મા યોજના (પરંપરાગત કારીગરો)", desc: "૧૮ પરંપરાગત કારીગરોને તાલીમ, ₹૧૫,૦૦૦ ટૂલકિટ અને ૫% વ્યાજે ₹૩ લાખની લોન." },
    pa: { name: "ਪੀਐਮ ਵਿਸ਼ਵਕਰਮਾ ਸਕੀਮ (ਰਵਾਇਤੀ ਦਸਤਕਾਰ)", desc: "੧੮ ਰਵਾਇਤੀ ਕਾਰੀਗਰਾਂ ਨੂੰ ਸਿਖਲਾਈ, ₹੧੫,੦੦੦ ਟੂਲਕਿੱਟ ਅਤੇ ੫% ਵਿਆਜ ਤੇ ₹੩ ਲੱਖ ਕਰਜ਼ਾ।" },
    or: { name: "ପିଏମ ବିଶ୍ୱକର୍ମା ଯୋଜନା (ପାରମ୍ପରିକ କାରିଗର)", desc: "୧୮ ପାରମ୍ପରିକ କାରିଗରଙ୍କୁ ପ୍ରଶିକ୍ଷଣ, ₹୧୫,୦୦୦ ଟୁଲକିଟ୍ ଏବଂ ୫% ସୁଧରେ ₹୩ ଲକ୍ଷ ଋଣ।" },
    as: { name: "পিএম বিশ্বকৰ্মা আঁচনি (পৰম্পৰাগত কাৰিকৰ আৰু শিল্পী)", desc: "১৮টা পৰম্পৰাগত বৃত্তিৰ বাবে প্ৰশিক্ষণ, ১৫,০০০ টকাৰ টুলকিট আৰু ৫% সুদেৰে ৩ লাখ টকা ঋণ।" }
  },
  NSFDC_EL: {
    hi: { name: "राष्ट्रीय अनुसूचित जाति वित्त निगम - शिक्षा ऋण (NSFDC)", desc: "अनुसूचित जाति के छात्रों को देश में ₹20 लाख व विदेश अध्ययन हेतु ₹30 लाख तक 4% ब्याज पर शिक्षा ऋण।" },
    ta: { name: "தேசிய ஆதிதிராவிடர் நிதி வளர்ச்சிக் கழக கல்விக்கடன் (NSFDC)", desc: "SC மாணவர்களுக்கு இந்தியாவில் ₹20 இலட்சம், வெளிநாட்டில் ₹30 இலட்சம் வரை 4% குறைந்த வட்டியில் கல்விக் கடன்." },
    te: { name: "ఎన్‌ఎస్‌ఎఫ్‌డిసి విద్యా రుణం (NSFDC)", desc: "ఎస్సీ విద్యార్థులకు భారతదేశంలో ₹20 లక్షలు, విదేశీ విద్యకు ₹30 లక్షల వరకు 4% వడ్డీతో విద్యా రుణం." }
  },
  CGFSEL: {
    hi: { name: "उच्च शिक्षा ऋण क्रेडिट गारंटी फंड (CGFSEL)", desc: "₹7.5 लाख तक के शिक्षा ऋण के लिए 100% संपार्श्विक-मुक्त बैंक गारंटी कवर।" },
    ta: { name: "கல்விக்கடன் கடன் உத்தரவாத நிதி (CGFSEL)", desc: "₹7.5 இலட்சம் வரையிலான கல்விக் கடன்களுக்கு 100% பிணையற்ற உத்தரவாதம்." },
    te: { name: "విద్యా రుణ క్రెడిట్ గ్యారెంటీ ఫండ్ (CGFSEL)", desc: "₹7.5 లక్షల వరకు గ్యారెంటీ లేని విద్యా రుణ రక్షణ." }
  },
  MUDRA_TARUN: {
    hi: { name: "प्रधानमंत्री मुद्रा योजना (तरुण श्रेणी)", desc: "स्थापित सूक्ष्म उद्यमों के विस्तार के लिए ₹5 लाख से ₹10 लाख तक बिना गारंटी कार्यशील पूंजी ऋण।" },
    ta: { name: "பிரதமரின் முத்ரா திட்டம் (தருண் பிரிவு)", desc: "தொழில் விரிவாக்கத்திற்கு பிணையற்ற ₹5 இலட்சம் முதல் ₹10 இலட்சம் வரை வங்கிக் கடன் உதவி." },
    te: { name: "ప్రధాన మంత్రి ముద్ర పథకం (తరుణ్)", desc: "వ్యాపార విస్తరణకు ₹5 లక్షల నుండి ₹10 లక్షల వరకు పూచీకత్తు లేని ముద్ర రుణం." }
  },
  MUDRA_KISHORE: {
    hi: { name: "प्रधानमंत्री मुद्रा योजना (किशोर श्रेणी)", desc: "₹50,000 से ₹5 लाख तक मध्यम कार्यशील पूंजी ऋण।" },
    ta: { name: "பிரதமரின் முத்ரா திட்டம் (கிஷோர் பிரிவு)", desc: "வளரும் தொழில்களுக்கு ₹50,000 முதல் ₹5 இலட்சம் வரை வங்கிக் கடன்." },
    te: { name: "ప్రధాన మంత్రి ముద్ర పథకం (కిశోర్)", desc: "రూ. 50,000 నుండి రూ. 5 లక్షల వరకు వ్యాపార రుణం." }
  },
  MUDRA_SHISHU: {
    hi: { name: "प्रधानमंत्री मुद्रा योजना (शिशु श्रेणी)", desc: "नए सूक्ष्म व्यवसाय हेतु ₹50,000 तक प्रारंभिक कार्यशील पूंजी ऋण।" },
    ta: { name: "பிரதமரின் முத்ரா திட்டம் (சிசு பிரிவு)", desc: "தொடக்க நிலை தொழில்களுக்கு ₹50,000 வரை பிணையற்ற கடன்." },
    te: { name: "ప్రధాన మంత్రి ముద్ర పథకం (శిశు)", desc: "రూ. 50,000 వరకు ప్రారంభ మూలధన రుణం." }
  }
};

export const DICTIONARY = {
  en: {
    appName: 'SCHEME SATHI',
    tagline: 'AI-Driven Scheme Matching for Marginalized Entrepreneurs',
    translationBadge: 'Powered by AI4Bharat Samanantar IndicNLP',
    sihBadgeText: 'SIH 2026',
    sihSubtext: 'Problem Statement ID: SIH26092 • AI-Driven Scheme Matching • Official myScheme.gov.in Dataset',
    navHome: 'Home',
    navHowItWorks: 'How It Works',
    navSchemes: 'Schemes',
    navFeatures: 'Features',
    navAbout: 'About',
    navLogin: 'Login',
    navRegister: 'Register',
    navDashboard: 'Dashboard',
    navFindScheme: 'Find My Scheme',
    navEmi: 'EMI Calculator',
    navDocAssistant: 'Doc Assistant',
    navPartners: 'Channel Partners',
    navChat: 'AI Assistant',
    navAdmin: 'Admin Portal',
    navProfile: 'User Profile',
    navHistory: 'Transparency Timeline',
    navLogout: 'Logout',
    find_my_scheme: 'Find My Scheme',
    btnFindScheme: 'Find My Scheme',
    btnChatAssistant: 'Chat with AI Assistant',
    btnExploreSchemes: 'Explore Schemes',
    btnCalculateEmi: 'Calculate EMI',
    btnCheckDocs: 'Check Documents',
    eligibleSchemes: 'Eligible Schemes',
    maxPotentialSubsidy: 'Max Potential Subsidy',
    applicationReadiness: 'Application Readiness',
    partnerBanksNearYou: 'Partner Banks Near You',
    dashboardOverview: 'Dashboard Overview',
    recommendationSubtitle: 'Real-time multi-factor government financial schemes matched against official gazetted criteria.',
    btnApplyDirect: 'Apply / Invite Partner',
    btnEmiPlan: 'Plan EMI',
    btnViewRules: 'View Rules',
    btnWhyEligible: 'Why am I eligible?',
    socialCategory: 'Social Category',
    gender: 'Gender',
    annualIncome: 'Annual Income',
    requiredLoan: 'Required Loan Amount',
    state: 'State',
    district: 'District',
    areaType: 'Area Classification',
    rural: 'Rural',
    urban: 'Urban',
    manufacturingOption: 'Manufacturing Unit',
    serviceOption: 'Service Sector',
    tradingOption: 'Trading / Retail',
    optionFemale: 'Woman / Female',
    optionMale: 'Male',
    optionTransgender: 'Transgender',
    docAadhaar: 'Aadhaar Card',
    docPan: 'PAN Card',
    docCaste: 'Caste Certificate',
    docIncome: 'Income Certificate',
    docDpr: 'Detailed Project Report (DPR)',
    docUdyam: 'Udyam Registration',
    doc10th: '10th Marksheet',
    doc12th: '12th Marksheet',
    docAdmission: 'Admission Letter',
    docFeeStructure: 'Fee Structure',
    docBank: 'Bank Statement',
    docEdp: 'EDP Training Certificate',
    unitLakh: 'Lakh',
    unitMonths: 'Months',
    specialRural: '35% Special Rural',
    lowInterest: 'Concessional Interest'
  },
  ta: {
    appName: 'ஸ்கீம் சாதி (SCHEME SATHI)',
    tagline: 'விளிம்புநிலை தொழில்முனைவோர் மற்றும் மாணவர்களுக்கான அரசு திட்டப் பொருத்தம்',
    translationBadge: 'AI4Bharat சமனந்தர் மொழிபெயர்ப்பு தொழில்நுட்பம்',
    sihBadgeText: 'SIH 2026',
    sihSubtext: 'ஸ்மார்ட் இந்தியா ஹேக்கத்தான் 2026 • AI அரசு திட்டப் பொருத்தம் • myScheme.gov.in அதிகாரப்பூர்வ தரவு',
    navHome: 'முகப்பு',
    navHowItWorks: 'எப்படி செயல்படுகிறது',
    navSchemes: 'அரசு திட்டங்கள்',
    navFeatures: 'அம்சங்கள்',
    navAbout: 'எங்களை பற்றி',
    navLogin: 'உள்நுழைவு',
    navRegister: 'பதிவு செய்க',
    navDashboard: 'டாஷ்போர்டு',
    navFindScheme: 'திட்டம் கண்டறிக',
    navEmi: 'EMI & மானியக் கணக்கீடு',
    navDocAssistant: 'ஆவண உதவியாளர் (OCR)',
    navPartners: 'வங்கி & உதவி மையங்கள்',
    navChat: 'AI வழிகாட்டி',
    navAdmin: 'நிர்வாக போர்டல்',
    navProfile: 'எனது சுயவிவரம்',
    navHistory: 'விண்ணப்ப வெளிப்படைத்தன்மை',
    navLogout: 'வெளியேறு',
    find_my_scheme: 'திட்டம் கண்டறிக',
    btnFindScheme: 'பொருத்தமான திட்டம் கண்டறிக',
    btnChatAssistant: 'AI வழிகாட்டியுடன் பேசுங்கள்',
    btnExploreSchemes: 'அனைத்து திட்டங்களையும் காண்க',
    btnCalculateEmi: 'EMI கணக்கிடுக',
    btnCheckDocs: 'ஆவணங்களை சரிபார்க்கவும்',
    eligibleSchemes: 'தகுதியான திட்டங்கள்',
    maxPotentialSubsidy: 'அதிகபட்ச சாத்தியமான மானியம்',
    applicationReadiness: 'விண்ணப்ப தயார்நிலை',
    partnerBanksNearYou: 'அருகிலுள்ள வங்கி கிளைகள்',
    dashboardOverview: 'டாஷ்போர்டு மேலோட்டம்',
    recommendationSubtitle: 'அரசாங்க விதிகளின்படி உங்களுக்கான பிரத்யேக அரசு உதவித் திட்டங்கள்.',
    btnApplyDirect: 'விண்ணப்பிக்க / வங்கிக்கு அனுப்புக',
    btnEmiPlan: 'EMI திட்டமிடுக',
    btnViewRules: 'விதிமுறைகளை காண்க',
    btnWhyEligible: 'நான் ஏன் தகுதியானவன்?',
    socialCategory: 'சமூகப் பிரிவு',
    gender: 'பாலினம்',
    annualIncome: 'ஆண்டு குடும்ப வருமானம்',
    requiredLoan: 'தேவையான கடன் தொகை',
    state: 'மாநிலம்',
    district: 'மாவட்டம்',
    areaType: 'பகுதி வகைப்பாடு',
    rural: 'கிராமப்புறம் (அதிக மானியம்)',
    urban: 'நகர்ப்புறம்',
    manufacturingOption: 'உற்பத்தித் தொழில் (35% வரை மானியம்)',
    serviceOption: 'சேவைத் தொழில்',
    tradingOption: 'வியாபாரம் / வர்த்தகம்',
    optionFemale: 'பெண் / மகளிர்',
    optionMale: 'ஆண்',
    optionTransgender: 'திருநங்கை',
    docAadhaar: 'ஆதார் அட்டை',
    docPan: 'பான் அட்டை',
    docCaste: 'சாதிச் சான்றிதழ்',
    docIncome: 'வருமானச் சான்றிதழ்',
    docDpr: 'திட்ட அறிக்கை (DPR)',
    docUdyam: 'உத்யம் பதிவு',
    doc10th: '10-ஆம் வகுப்பு மதிப்பெண் பட்டியல்',
    doc12th: '12-ஆம் வகுப்பு மதிப்பெண் பட்டியல்',
    docAdmission: 'சேர்க்கை ஆணை',
    docFeeStructure: 'கட்டண விவரம்',
    docBank: 'வங்கி கணக்கு அறிக்கை',
    docEdp: 'EDP பயிற்சி சான்றிதழ்',
    unitLakh: 'இலட்சம்',
    unitMonths: 'மாதங்கள்',
    specialRural: '35% கிராமப்புற சிறப்பு மானியம்',
    lowInterest: 'குறைந்த வட்டி சலுகை'
  },
  hi: {
    appName: 'स्कीम साथी (SCHEME SATHI)',
    tagline: 'उद्यमियों एवं छात्रों के लिए एआई-संचालित सरकारी योजना मिलान',
    translationBadge: 'AI4Bharat समानांतर IndicNLP द्वारा संचालित',
    sihBadgeText: 'SIH 2026',
    sihSubtext: 'स्मार्ट इंडिया हैकथॉन 2026 • आधिकारिक myScheme.gov.in डेटासेट',
    navHome: 'होम',
    navHowItWorks: 'यह कैसे काम करता है',
    navSchemes: 'सरकारी योजनाएं',
    navFeatures: 'विशेषताएं',
    navAbout: 'हमारे बारे में',
    navLogin: 'लॉग इन',
    navRegister: 'पंजीकरण करें',
    navDashboard: 'डैशबोर्ड',
    navFindScheme: 'योजना खोजें',
    navEmi: 'ईएमआई कैलकुलेटर',
    navDocAssistant: 'दस्तावेज़ सहायक (OCR)',
    navPartners: 'बैंक व भागीदार',
    navChat: 'एआई सहायक',
    navAdmin: 'प्रशासन पोर्टल',
    navProfile: 'उपयोगकर्ता प्रोफ़ाइल',
    navHistory: 'आवेदन पारदर्शिता टाइमलाइन',
    navLogout: 'लॉग आउट',
    find_my_scheme: 'योजना खोजें',
    btnFindScheme: 'अपनी योजना खोजें',
    btnChatAssistant: 'एआई सहायक से बात करें',
    btnExploreSchemes: 'सभी योजनाएं देखें',
    btnCalculateEmi: 'ईएमआई की गणना करें',
    btnCheckDocs: 'दस्तावेज़ सत्यापित करें',
    eligibleSchemes: 'पात्र योजनाएं',
    maxPotentialSubsidy: 'अधिकतम संभावित सब्सिडी',
    applicationReadiness: 'आवेदन तैयारी स्तर',
    partnerBanksNearYou: 'निकटतम बैंक शाखाएं',
    dashboardOverview: 'डैशबोर्ड अवलोकन',
    recommendationSubtitle: 'आधिकारिक राजपत्रित नियमों के आधार पर आपके लिए उपयुक्त सरकारी योजनाएं।',
    btnApplyDirect: 'आवेदन करें / बैंक को भेजें',
    btnEmiPlan: 'ईएमआई की योजना बनाएं',
    btnViewRules: 'नियम देखें',
    btnWhyEligible: 'मेरी पात्रता का कारण?',
    socialCategory: 'सामाजिक श्रेणी',
    gender: 'लिंग',
    annualIncome: 'वार्षिक पारिवारिक आय',
    requiredLoan: 'आवश्यक ऋण राशि',
    state: 'राज्य',
    district: 'जिला',
    areaType: 'क्षेत्र वर्गीकरण',
    rural: 'ग्रामीण (उच्चतम सब्सिडी)',
    urban: 'शहरी',
    manufacturingOption: 'विनिर्माण उद्योग (35% तक सब्सिडी)',
    serviceOption: 'सेवा क्षेत्र',
    tradingOption: 'व्यापार / ट्रेडिंग',
    optionFemale: 'महिला',
    optionMale: 'पुरुष',
    optionTransgender: 'ट्रांसजेंडर',
    docAadhaar: 'आधार कार्ड',
    docPan: 'पैन कार्ड',
    docCaste: 'जाति प्रमाण पत्र',
    docIncome: 'आय प्रमाण पत्र',
    docDpr: 'विस्तृत परियोजना रिपोर्ट (DPR)',
    docUdyam: 'उद्यम पंजीकरण',
    doc10th: '10वीं अंकतालिका',
    doc12th: '12वीं अंकतालिका',
    docAdmission: 'प्रवेश पत्र (ऑफर लेटर)',
    docFeeStructure: 'फीस संरचना',
    docBank: 'बैंक खाता विवरण',
    docEdp: 'ईडीपी प्रशिक्षण प्रमाण पत्र',
    unitLakh: 'लाख',
    unitMonths: 'महीने',
    specialRural: '35% विशेष ग्रामीण सब्सिडी',
    lowInterest: 'रियायती ब्याज दर'
  },
  te: {
    appName: 'స్కీమ్ సాథి (SCHEME SATHI)',
    tagline: 'అర్హులైన పారిశ్రామికవేత్తలు మరియు విద్యార్థుల కోసం ప్రభుత్వ పథకాల గుర్తింపు',
    translationBadge: 'AI4Bharat సమనాంతర్ ఆధారితం',
    sihBadgeText: 'SIH 2026',
    sihSubtext: 'స్మార్ట్ ఇండియా హ్యాకథాన్ 2026 • myScheme.gov.in అధికారిక సమాచారం',
    navHome: 'హోమ్',
    navHowItWorks: 'ఎలా పనిచేస్తుంది',
    navSchemes: 'పథకాలు',
    navFeatures: 'ఫీచర్లు',
    navAbout: 'మా గురించి',
    navLogin: 'లాగిన్',
    navRegister: 'నమోదు చేసుకోండి',
    navDashboard: 'డ్యాష్‌బోర్డ్',
    navFindScheme: 'పథకాన్ని కనుగొనండి',
    navEmi: 'ఈఎంఐ కాలిక్యులేటర్',
    navDocAssistant: 'పత్రాల సహాయకుడు (OCR)',
    navPartners: 'బ్యాంకు శాఖలు',
    navChat: 'ఏఐ సహాయకుడు',
    navAdmin: 'అడ్మిన్ పోర్టల్',
    navProfile: 'ప్రొఫైల్',
    navHistory: 'దరఖాస్తు స్థితి',
    navLogout: 'లాగ్ అవుట్',
    find_my_scheme: 'పథకాన్ని కనుగొనండి',
    btnFindScheme: 'నా పథకాన్ని కనుగొనండి',
    btnChatAssistant: 'ఏఐతో మాట్లాడండి',
    btnExploreSchemes: 'పథకాలను చూడండి',
    btnCalculateEmi: 'ఈఎంఐ లెక్కించండి',
    btnCheckDocs: 'పత్రాలను తనిఖీ చేయండి',
    eligibleSchemes: 'అర్హతగల పథకాలు',
    maxPotentialSubsidy: 'గరిష్ట సంభావ్య సబ్సిడీ',
    applicationReadiness: 'దరఖాస్తు సంసిద్ధత',
    partnerBanksNearYou: 'సమీప బ్యాంకు శాఖలు',
    dashboardOverview: 'డ్యాష్‌బోర్డ్ అవలోకనం',
    btnApplyDirect: 'దరఖాస్తు చేయండి / బ్యాంకుకు పంపండి',
    btnEmiPlan: 'ఈఎంఐ ప్లాన్ చేయండి',
    btnViewRules: 'నిబంధనలు చూడండి',
    btnWhyEligible: 'నేను ఎందుకు అర్హుడను?',
    socialCategory: 'సామాజిక వర్గం',
    gender: 'లింగం',
    annualIncome: 'వార్షిక కుటుంబ ఆదాయం',
    requiredLoan: 'కావలసిన రుణ మొత్తం',
    state: 'రాష్ట్రం',
    district: 'జిల్లా',
    areaType: 'ప్రాంత వర్గీకరణ',
    rural: 'గ్రామీణ (అధిక సబ్సిడీ)',
    urban: 'పట్టణ',
    manufacturingOption: 'ఉత్పాదక రంగం',
    serviceOption: 'సేవా రంగం',
    tradingOption: 'వ్యాపారం',
    optionFemale: 'మహిళ',
    optionMale: 'పురుషుడు',
    optionTransgender: 'ట్రాన్స్‌జెండర్',
    docAadhaar: 'ఆధార్ కార్డు',
    docPan: 'పాన్ కార్డు',
    docCaste: 'కుల ధృవీకరణ పత్రం',
    docIncome: 'ఆదాయ ధృవీకరణ పత్రం',
    docDpr: 'ప్రాజెక్ట్ నివేదిక (DPR)',
    docUdyam: 'ఉద్యమ్ రిజిస్ట్రేషన్',
    doc10th: '10వ తరగతి మార్కుల జాబితా',
    doc12th: '12వ తరగతి మార్కుల జాబితా',
    docAdmission: 'అడ్మిషన్ లెటర్',
    docFeeStructure: 'ఫీజు వివరాలు',
    docBank: 'బ్యాంక్ స్టేట్‌మెంట్',
    docEdp: 'EDP శిక్షణ పత్రం',
    unitLakh: 'లక్షలు',
    unitMonths: 'నెలలు',
    specialRural: '35% ప్రత్యేక గ్రామీణ సబ్సిడీ',
    lowInterest: 'తక్కువ వడ్డీ రాయితీ'
  }
};

// Auto-fill other Indic dictionaries from Hindi if missing
['kn', 'ml', 'mr', 'bn', 'gu', 'pa', 'or', 'as'].forEach(code => {
  if (!DICTIONARY[code]) {
    DICTIONARY[code] = { ...DICTIONARY.hi };
  }
});

export const PHRASE_MAP = {
  ta: {
    "find my scheme": "திட்டம் கண்டறிக",
    "step 1: choose your primary focus / objective": "படி 1: உங்கள் முதன்மை நோக்கத்தைத் தேர்வுசெய்க",
    "education & student loans": "கல்வி மற்றும் மாணவர் கடன்கள்",
    "csis 100% interest subsidy, nsfdc, nbcfdc, cgfsel up to ₹7.5l collateral-free.": "CSIS 100% முழு வட்டி மானியம், NSFDC, NBCFDC, CGFSEL ₹7.5 இலட்சம் வரை பிணையற்ற கடன்.",
    "6 verified schemes": "6 சரிபார்க்கப்பட்ட திட்டங்கள்",
    "business & enterprise setup": "தொழில் & புதிய தொழில் நிறுவனங்கள்",
    "pmegp up to 35% margin grant, stand-up india up to ₹1 cr, state cmegp/needs.": "PMEGP 35% வரை மானியம், ஸ்டாண்ட்-அப் இந்தியா ₹1 கோடி வரை, மாநில CMEGP திட்டங்கள்.",
    "12 verified schemes": "12 சரிபார்க்கப்பட்ட திட்டங்கள்",
    "self-employment & artisans": "சுயதொழில் மற்றும் கைவினைஞர்கள்",
    "pm svanidhi 7% subvention, pm vishwakarma toolkit grant & ₹3l concessional credit.": "PM ஸ்வநிதி 7% வட்டி மானியம், PM விஸ்வகர்மா ₹15,000 கருவி மானியம் & ₹3 இலட்சம் கடன்.",
    "5 verified schemes": "5 சரிபார்க்கப்பட்ட திட்டங்கள்",
    "applicant profile & demographics": "விண்ணப்பதாரர் சுயவிவரம்",
    "academic & financial details": "கல்வி மற்றும் நிதி விவரங்கள்",
    "enterprise & financial quantum": "தொழில் மற்றும் நிதித் தேவைகள்",
    "review & unlock documents": "சுயவிவரத்தை சரிபார்த்து உறுதிப்படுத்துக",
    "applicant eligibility profile": "விண்ணப்பதாரர் தகுதி சுயவிவரம்",
    "these core parameters determine statutory quotas, interest subventions, and eligibility bands.": "இந்த அடிப்படை விவரங்கள் உங்கள் அரசு இடஒதுக்கீடு, வட்டி மானியம் மற்றும் தகுதி நிலையை நிர்ணயிக்கின்றன.",
    "eligible schemes": "தகுதியான திட்டங்கள்",
    "max potential subsidy": "அதிகபட்ச சாத்தியமான மானியம்",
    "application readiness": "விண்ணப்ப தயார்நிலை",
    "partner banks near you": "அருகிலுள்ள வங்கி கிளைகள்",
    "100% rule verified": "100% விதிமுறைகள் சரிபார்க்கப்பட்டது",
    "country": "நாடு",
    "state / union territory": "மாநிலம் / யூனியன் பிரதேசம்",
    "state / ut": "மாநிலம் / யூனியன் பிரதேசம்",
    "state": "மாநிலம்",
    "district": "மாவட்டம்",
    "area classification": "பகுதி வகைப்பாடு",
    "area setting": "பகுதி வகைப்பாடு",
    "rural": "கிராமப்புறம் (அதிக மானியம்)",
    "urban": "நகர்ப்புறம்",
    "previous": "முந்தைய படி",
    "next step": "அடுத்த படி",
    "confirm & save profile": "சுயவிவரத்தை சேமித்து உறுதிப்படுத்துக",
    "confirm & proceed to document assistant": "உறுதிசெய்து ஆவண உதவியாளரிடம் செல்லவும்",
    "full name": "முழு பெயர்",
    "age (years)": "வயது (ஆண்டுகள்)",
    "gender": "பாலினம்",
    "female": "பெண்",
    "male": "ஆண்",
    "transgender": "திருநங்கை",
    "total project cost (₹)": "மொத்த திட்ட மதிப்பீடு (₹)",
    "required loan amount (₹)": "தேவையான கடன் தொகை (₹)",
    "annual family income (₹)": "ஆண்டு குடும்ப வருமானம் (₹)",
    "target marginalized category": "சமூகப் பிரிவு (இடஒதுக்கீடு & மானியம்)",
    "target marginalized category (drives special subsidies)": "சமூகப் பிரிவு (சிறப்பு மானியங்களை நிர்ணயிக்கிறது)",
    "general category": "பொதுப் பிரிவு (General)",
    "scheduled caste (sc)": "பட்டியலினத்தவர் (SC)",
    "scheduled tribe (st)": "பழங்குடியினர் (ST)",
    "other backward classes (obc)": "இதர பிற்படுத்தப்பட்டோர் (OBC)",
    "minority community": "சிறுபான்மையினர் சமூகம்",
    "women entrepreneur / special category": "பெண் தொழில்முனைவோர் / சிறப்புப் பிரிவு",
    "specially abled / divyangjan": "மாற்றுத்திறனாளி (திவ்யாங்ஜன்)",
    "1. profile": "1. சுயவிவரம்",
    "2. requirement": "2. தேவை விவரம்",
    "3. documents": "3. ஆவணங்கள்",
    "4. eligibility": "4. தகுதி நிலை",
    "5. scheme": "5. திட்ட தேர்வு",
    "6. emi": "6. EMI விவரம்",
    "7. partner map": "7. வங்கி வரைபடம்",
    "current": "தற்போதைய நிலை",
    "completed": "முடிக்கப்பட்டது",
    "locked": "பூட்டப்பட்டுள்ளது",
    "locked 🔒": "பூட்டப்பட்டுள்ளது 🔒",
    "next": "அடுத்தது",
    "selected track:": "தேர்ந்தெடுக்கப்பட்ட பாதை:",
    "social category:": "சமூகப் பிரிவு:",
    "annual family income:": "ஆண்டு குடும்ப வருமானம்:",
    "required loan amount:": "தேவையான கடன் தொகை:",
    "resident location:": "இருப்பிடம்:",
    "target course:": "பாடப்பிரிவு:",
    "enterprise activity:": "தொழில் வகை:",
    "next step: document assistant verification": "அடுத்த படி: ஆவண சரிபார்ப்பு உதவியாளர்",
    "review & confirm profile": "சுயவிவரத்தை சரிபார்த்து உறுதிப்படுத்துக",
    "tamil nadu": "தமிழ்நாடு",
    "maharashtra": "மகாராஷ்டிரா",
    "karnataka": "கர்நாடகா",
    "kerala": "கேரளா",
    "delhi": "தில்லி",
    "gujarat": "குஜராத்",
    "andhra pradesh": "ஆந்திரப் பிரதேசம்",
    "telangana": "தெலுங்கானா",
    "tiruvallur": "திருவள்ளூர்",
    "chennai": "சென்னை",
    "coimbatore": "கோயம்புத்தூர்",
    "madurai": "மதுரை",
    "salem": "சேலம்",
    "tiruchirappalli": "திருச்சிராப்பள்ளி",
    "kancheepuram": "காஞ்சிபுரம்",
    "tirunelveli": "திருநெல்வேலி",
    "vellore": "வேலூர்",
    "erode": "ஈரோடு",
    "dindigul": "திண்டுக்கல்",
    "thanjavur": "தஞ்சாவூர்",
    "cuddalore": "கடலூர்",
    "dharmapuri": "தருமபுரி",
    "karur": "கரூர்",
    "nagapattinam": "நாகப்பட்டினம்",
    "namakkal": "நாமக்கல்",
    "perambalur": "பெரம்பலூர்",
    "pudukkottai": "புதுக்கோட்டை",
    "ramanathapuram": "ராமநாதபுரம்",
    "sivaganga": "சிவகங்கை",
    "the nilgiris": "நீலகிரி",
    "theni": "தேனி",
    "thiruvannamalai": "திருவண்ணாமலை",
    "thiruvarur": "திருவாரூர்",
    "thoothukkudi": "தூத்துக்குடி",
    "tiruppur": "திருப்பூர்",
    "viluppuram": "விழுப்புரம்",
    "virudhunagar": "விருதுநகர்",
    "ariyalur": "அரியலூர்",
    "krishnagiri": "கிருஷ்ணகிரி",
    "ranipet": "ராணிப்பேட்டை",
    "tenkasi": "தென்காசி",
    "tirupathur": "திருப்பத்தூர்",
    "chengalpattu": "செங்கல்பட்டு",
    "kallakurichi": "கள்ளக்குறிச்சி",
    "mayiladuthurai": "மயிலாடுதுறை",
    "dashboard overview": "டாஷ்போர்டு மேலோட்டம்",
    "requirement questionnaire": "தேவை கேள்வித்தாள்",
    "recommended schemes": "பரிந்துரைக்கப்பட்ட திட்டங்கள்",
    "financial / emi calculator": "நிதி / EMI கணக்கீடு",
    "document assistant (ocr)": "ஆவண உதவியாளர் (OCR)",
    "document checklist": "ஆவண சரிபார்ப்பு பட்டியல்",
    "channel partner locator": "வங்கி மற்றும் உதவி மையங்கள்",
    "scheme sathi ai chat": "AI வழிகாட்டி உரையாடல்",
    "saved schemes & history": "சேமிக்கப்பட்ட திட்டங்கள் & வரலாறு",
    "notifications": "அறிவிப்புகள்",
    "my profile": "எனது சுயவிவரம்",
    "sign out": "வெளியேறு",
    "admin portal": "நிர்வாக போர்டல்",
    "switch to user view": "பயனர் பார்வைக்கு மாறவும்",
    "select your goal track": "உங்கள் இலக்கு பாதையைத் தேர்ந்தெடுக்கவும்",
    "target course / loan amount": "பாடப்பிரிவு / தேவையான கடன் தொகை",
    "course stream": "பாடப்பிரிவு",
    "activity type": "தொழில் வகை",
    "business nature": "தொழில் தன்மை",
    "location setting": "இருப்பிட வகை",
    "manufacturing": "உற்பத்தித் துறை",
    "service": "சேவைத் துறை",
    "trading": "வர்த்தகம் / விற்பனை",
    "street vendor / hawkers": "தெருவோர வியாபாரி",
    "artisan / handicrafts": "கைவினைஞர் / கைவினைத் தொழில்",
    "small service / repair": "சிறிய சேவை / பழுது பார்த்தல்",
    "engineering / tech": "பொறியியல் / தொழில்நுட்பம்",
    "medical / healthcare": "மருத்துவம் / சுகாதாரத் துறை",
    "management / mba": "மேலாண்மை / MBA",
    "overseas studies": "வெளிநாட்டுப் படிப்பு",
    "street view": "தெரு வரைபடம்",
    "satellite": "செயற்கைக்கோள் பார்வை",
    "offline grid": "ஆஃப்லைன் வரைபடம்",
    "verify dbt account": "DBT வங்கிக் கணக்கை சரிபார்க்கவும்",
    "listen aloud": "ஒலியில் கேட்கவும்",
    "open live gps navigation": "நேரடி GPS வழிகாட்டலைத் திறக்கவும்",
    "call branch": "கிளையை அழைக்கவும்",
    "processing bank & channel partner locator": "வங்கி கிளை & உதவி மைய இருப்பிடம்",
    "assign & dispatch application": "விண்ணப்பத்தை ஒதுக்கி வங்கிக்கு அனுப்புக",
    "send application invitation": "வங்கிக்கு விண்ணப்ப அழைப்பை அனுப்புக",
    "channel partner invitation dispatched": "வங்கிக்கு விண்ணப்ப அழைப்பு வெற்றிகரமாக அனுப்பப்பட்டது",
    "application readiness assessment": "விண்ணப்ப தயார்நிலை மதிப்பீடு",
    "sanction confidence scorecard": "வங்கி ஒப்புதல் சாத்தியக்கூறு மதிப்பெண்",
    "overall submission score": "ஒட்டுமொத்த தயார்நிலை மதிப்பெண்",
    "high sanction probability": "அதிக ஒப்புதல் வாய்ப்பு",
    "1. profile demographics completeness": "1. சுயவிவர முழுமைத்தன்மை",
    "2. deterministic rule engine eligibility": "2. அரசாங்க விதிமுறைகள் தகுதி",
    "3. ocr document verification": "3. OCR ஆவண சரிபார்ப்பு",
    "4. partner bank routing": "4. அருகிலுள்ள வங்கி இணைப்பு",
    "notifications & alerts": "அறிவிப்புகள் & எச்சரிக்கைகள்",
    "gazette policy updates and application reminders": "அரசு கொள்கை மாற்றங்கள் மற்றும் விண்ணப்ப நினைவூட்டல்கள்",
    "email address": "மின்னஞ்சல் முகவரி",
    "password": "கடவுச்சொல்",
    "sign in": "உள்நுழையவும்",
    "authenticating...": "சரிபார்க்கிறது...",
    "quick demo login:": "விரைவு டெமோ உள்நுழைவு:",
    "woman founder": "பெண் தொழில்முனைவோர்",
    "street vendor": "தெருவோர வியாபாரி",
    "create entrepreneur profile": "புதிய சுயவிவரத்தை உருவாக்கவும்",
    "rapid requirement questionnaire": "விரைவு தேவை கேள்வித்தாள்",
    "directly adjust financial parameters to see scheme eligibility recalculate instantly.": "நிதி அளவீடுகளை மாற்றி திட்ட தகுதியை உடனடியாக கணக்கிடுங்கள்.",
    "run real-time scheme compatibility": "நிகழ்நேர திட்ட பொருத்தத்தை இயக்கவும்",
    "evaluating...": "மதிப்பிடுகிறது...",
    "shap-style factor attribution & rule compliance": "காரணி விளக்கம் மற்றும் விதிமுறை இணக்கம்",
    "positive contributing factors (+ impact)": "நேர்மறை தகுதி காரணிகள் (+ பயன்)",
    "limiting / disqualifying factors (- impact)": "தகுதிக் குறைபாடு காரணிகள் (- பாதிப்பு)",
    "ready to proceed with application?": "விண்ணப்பத்துடன் தொடர தயாரா?",
    "calculate exact monthly emis after 35% subsidy or locate your nearest nodal bank.": "35% மானியத்திற்குப் பிந்தைய EMI கணக்கிடுங்கள் அல்லது அருகிலுள்ள வங்கியைத் தொடர்பு கொள்ளுங்கள்.",
    "back to matching results": "பொருந்திய திட்டங்களின் முடிவுகளுக்குத் திரும்புக",
    "back to scheme results": "திட்ட முடிவுகளுக்குத் திரும்புக",
    "official portal": "அதிகாரப்பூர்வ போர்டல்",
    "loading statutory gazette scheme details from myscheme.gov.in records...": "myScheme.gov.in பதிவுகளிலிருந்து விவரங்கள் ஏற்றப்படுகின்றன...",
    "monthly emi": "மாதாந்திர EMI",
    "total interest payable": "மொத்த வட்டித் தொகை",
    "total amount payable": "மொத்த திருப்பிச் செலுத்தும் தொகை",
    "capital subsidy amount": "அரசு மூலதன மானியத் தொகை",
    "net loan principal after subsidy": "மானியத்திற்குப் பிந்தைய நிகர கடன் தொகை",
    "moratorium period": "அதிஸ்தகனக் காலம் (தவணை விடுமுறை)",
    "loan quantum (₹)": "கடன் தொகை (₹)",
    "tenure (years)": "திருப்பிச் செலுத்தும் காலம் (ஆண்டுகள்)",
    "annual interest rate (%)": "ஆண்டு வட்டி விகிதம் (%)",
    "applicable subsidy (%)": "பொருந்தக்கூடிய மானியம் (%)",
    "moratorium / grace period (months)": "தவணை விடுமுறை காலம் (மாதங்கள்)",
    "emi & capital subsidy calculator": "EMI & மூலதன மானியக் கணக்கீடு",
    "amortization schedule": "மாதாந்திர கடன் திருப்பிச் செலுத்தும் அட்டவணை",
    "month": "மாதம்",
    "principal paid": "அசல் தொகை",
    "interest paid": "வட்டித் தொகை",
    "remaining balance": "மீதமுள்ள கடன் தொகை",
    "print emi summary": "EMI சுருக்கத்தை அச்சிடுக",
    "document vault (indexed)": "ஆவண பெட்டகம் (சரிபார்க்கப்பட்டது)",
    "upload file (ocr)": "ஆவணத்தை பதிவேற்றுக (OCR)",
    "1-click synthetic samples": "1-கிளிக் மாதிரி ஆவணங்கள்",
    "direct text stream": "நேரடி உரை சரிபார்ப்பு",
    "multilingual ocr document assistant": "பன்மொழி OCR ஆவண உதவியாளர்",
    "auto-extract, pre-validate & hash documents": "ஆவணங்களிலிருந்து விவரங்களை பிரித்தெடுத்து முன்கூட்டியே சரிபார்க்கவும்",
    "verified": "சரிபார்க்கப்பட்டது",
    "pending": "நிலுவையில் உள்ளது",
    "optional": "விருப்பத்தேர்வு",
    "mandatory": "கட்டாயம்",
    "document audit logs": "ஆவண தணிக்கை பதிவுகள்"
  },
  hi: {
    "find my scheme": "योजना खोजें",
    "step 1: choose your primary focus / objective": "चरण 1: अपना प्राथमिक उद्देश्य चुनें",
    "education & student loans": "शिक्षा एवं छात्र ऋण",
    "csis 100% interest subsidy, nsfdc, nbcfdc, cgfsel up to ₹7.5l collateral-free.": "CSIS 100% पूर्ण ब्याज सब्सिडी, NSFDC, NBCFDC, CGFSEL ₹7.5 लाख तक बिना गारंटी ऋण।",
    "6 verified schemes": "6 सत्यापित योजनाएं",
    "business & enterprise setup": "व्यवसाय एवं उद्योग स्थापना",
    "pmegp up to 35% margin grant, stand-up india up to ₹1 cr, state cmegp/needs.": "PMEGP 35% तक सब्सिडी, स्टैंड-अप इंडिया ₹1 करोड़ तक, राज्य CMEGP/NEEDS योजनाएं।",
    "12 verified schemes": "12 सत्यापित योजनाएं",
    "self-employment & artisans": "स्वरोजगार एवं कारीगर",
    "pm svanidhi 7% subvention, pm vishwakarma toolkit grant & ₹3l concessional credit.": "पीएम स्वनिधि 7% ब्याज सब्सिडी, पीएम विश्वकर्मा ₹15,000 टूलकिट अनुदान और ₹3 लाख ऋण।",
    "5 verified schemes": "5 सत्यापित योजनाएं",
    "applicant profile & demographics": "आवेदक प्रोफ़ाइल एवं विवरण",
    "academic & financial details": "शैक्षणिक और वित्तीय विवरण",
    "enterprise & financial quantum": "उद्यम और वित्तीय आवश्यकताएं",
    "review & unlock documents": "समीक्षा करें और दस्तावेज़ अनलॉक करें",
    "applicant eligibility profile": "आवेदक पात्रता प्रोफ़ाइल",
    "these core parameters determine statutory quotas, interest subventions, and eligibility bands.": "ये मुख्य पैरामीटर वैधानिक कोटा, ब्याज सब्सिडी और पात्रता स्तर निर्धारित करते हैं।",
    "eligible schemes": "पात्र योजनाएं",
    "max potential subsidy": "अधिकतम संभावित सब्सिडी",
    "application readiness": "आवेदन तैयारी",
    "partner banks near you": "निकटतम बैंक शाखाएं",
    "100% rule verified": "100% नियम सत्यापित",
    "country": "देश",
    "state / union territory": "राज्य / केंद्र शासित प्रदेश",
    "state / ut": "राज्य / केंद्र शासित प्रदेश",
    "state": "राज्य",
    "district": "जिला",
    "area classification": "क्षेत्र वर्गीकरण",
    "area setting": "क्षेत्र वर्गीकरण",
    "rural": "ग्रामीण (अधिकतम सब्सिडी)",
    "urban": "शहरी",
    "previous": "पिछला कदम",
    "next step": "अगला कदम",
    "confirm & save profile": "प्रोफ़ाइल सहेजें एवं पुष्टि करें",
    "confirm & proceed to document assistant": "पुष्टि करें और दस्तावेज़ सहायक पर जाएं",
    "full name": "पूरा नाम",
    "age (years)": "आयु (वर्ष)",
    "gender": "लिंग",
    "female": "महिला",
    "male": "पुरुष",
    "transgender": "ट्रांसजेंडर",
    "total project cost (₹)": "कुल परियोजना लागत (₹)",
    "required loan amount (₹)": "आवश्यक ऋण राशि (₹)",
    "annual family income (₹)": "वार्षिक पारिवारिक आय (₹)",
    "target marginalized category": "सामाजिक श्रेणी (आरक्षण एवं सब्सिडी)",
    "target marginalized category (drives special subsidies)": "सामाजिक श्रेणी (विशेष सब्सिडी को निर्धारित करती है)",
    "general category": "सामान्य वर्ग (General)",
    "scheduled caste (sc)": "अनुसूचित जाति (SC)",
    "scheduled tribe (st)": "अनुसूचित जनजाति (ST)",
    "other backward classes (obc)": "अन्य पिछड़ा वर्ग (OBC)",
    "minority community": "अल्पसंख्यक समुदाय",
    "women entrepreneur / special category": "महिला उद्यमी / विशेष श्रेणी",
    "specially abled / divyangjan": "दिव्यांगजन",
    "1. profile": "1. प्रोफ़ाइल",
    "2. requirement": "2. आवश्यकताएं",
    "3. documents": "3. दस्तावेज़",
    "4. eligibility": "4. पात्रता",
    "5. scheme": "5. योजना",
    "6. emi": "6. EMI",
    "7. partner map": "7. बैंक मानचित्र",
    "current": "वर्तमान",
    "completed": "पूर्ण",
    "locked": "लॉक किया गया",
    "locked 🔒": "लॉक 🔒",
    "next": "अगला",
    "selected track:": "चयनित श्रेणी:",
    "social category:": "सामाजिक श्रेणी:",
    "annual family income:": "वार्षिक पारिवारिक आय:",
    "required loan amount:": "आवश्यक ऋण राशि:",
    "resident location:": "निवास स्थान:",
    "target course:": "पाठ्यक्रम:",
    "enterprise activity:": "उद्यम गतिविधि:",
    "next step: document assistant verification": "अगला चरण: दस्तावेज़ सहायक सत्यापन",
    "review & confirm profile": "समीक्षा करें और प्रोफ़ाइल की पुष्टि करें",
    "tamil nadu": "तमिलनाडु",
    "maharashtra": "महाराष्ट्र",
    "karnataka": "कर्नाटक",
    "kerala": "केरल",
    "delhi": "दिल्ली",
    "gujarat": "गुजरात",
    "andhra pradesh": "आंध्र प्रदेश",
    "telangana": "तेलंगाना",
    "dashboard overview": "डैशबोर्ड अवलोकन",
    "requirement questionnaire": "आवश्यकता प्रश्नावली",
    "recommended schemes": "अनुशंसित योजनाएं",
    "financial / emi calculator": "वित्तीय / ईएमआई कैलकुलेटर",
    "document assistant (ocr)": "दस्तावेज़ सहायक (OCR)",
    "document checklist": "दस्तावेज़ चेकलिस्ट",
    "channel partner locator": "बैंक शाखा एवं सहायता केंद्र",
    "scheme sathi ai chat": "एआई सहायक संवाद",
    "saved schemes & history": "सहेजी गई योजनाएं और इतिहास",
    "notifications": "सूचनाएं",
    "my profile": "मेरी प्रोफ़ाइल",
    "sign out": "लॉग आउट",
    "admin portal": "एडमिन पोर्टल",
    "switch to user view": "उपयोगकर्ता दृश्य पर जाएं",
    "select your goal track": "अपना लक्ष्य चुनें",
    "target course / loan amount": "पाठ्यक्रम / आवश्यक ऋण राशि",
    "course stream": "पाठ्यक्रम",
    "activity type": "गतिविधि का प्रकार",
    "business nature": "व्यवसाय की प्रकृति",
    "location setting": "स्थान का प्रकार",
    "manufacturing": "विनिर्माण उद्योग",
    "service": "सेवा क्षेत्र",
    "trading": "व्यापार / खुदरा",
    "street vendor / hawkers": "स्ट्रीट वेंडर / फेरीवाले",
    "artisan / handicrafts": "कारीगर / हस्तशिल्प",
    "small service / repair": "मरम्मत व सेवा कार्य",
    "engineering / tech": "इंजीनियरिंग / तकनीकी",
    "medical / healthcare": "चिकित्सा / स्वास्थ्य",
    "management / mba": "प्रबंधन / एमबीए",
    "overseas studies": "विदेश में उच्च शिक्षा",
    "street view": "सड़क दृश्य",
    "satellite": "सैटेलाइट दृश्य",
    "offline grid": "ऑफ़लाइन ग्रिड",
    "verify dbt account": "डीबीटी बैंक खाता सत्यापित करें",
    "listen aloud": "बोलकर सुनें",
    "open live gps navigation": "लाइव जीपीएस नेविगेशन खोलें",
    "call branch": "शाखा को कॉल करें",
    "processing bank & channel partner locator": "बैंक शाखा एवं चैनल पार्टनर लोकेटर",
    "assign & dispatch application": "आवेदन बैंक को भेजें",
    "send application invitation": "बैंक को आवेदन आमंत्रण भेजें",
    "channel partner invitation dispatched": "बैंक को आवेदन आमंत्रण सफलतापूर्वक भेजा गया",
    "application readiness assessment": "आवेदन तैयारी मूल्यांकन",
    "sanction confidence scorecard": "ऋण स्वीकृति स्कोरकार्ड",
    "overall submission score": "कुल प्रस्तुति स्कोर",
    "high sanction probability": "उच्च स्वीकृति संभावना",
    "1. profile demographics completeness": "1. प्रोफ़ाइल पूर्णता",
    "2. deterministic rule engine eligibility": "2. नियम इंजन पात्रता",
    "3. ocr document verification": "3. ओसीआर दस्तावेज़ सत्यापन",
    "4. partner bank routing": "4. निकटतम बैंक मैपिंग",
    "notifications & alerts": "सूचनाएं एवं अलर्ट",
    "gazette policy updates and application reminders": "राजपत्रित नीति अपडेट और आवेदन अनुस्मारक",
    "email address": "ईमेल पता",
    "password": "पासवर्ड",
    "sign in": "साइन इन करें",
    "authenticating...": "प्रमाणीकरण जारी है...",
    "quick demo login:": "त्वरित डेमो लॉगिन:",
    "woman founder": "महिला उद्यमी",
    "street vendor": "स्ट्रीट वेंडर",
    "create entrepreneur profile": "नया उद्यमी प्रोफ़ाइल बनाएं",
    "rapid requirement questionnaire": "त्वरित आवश्यकता प्रश्नावली",
    "directly adjust financial parameters to see scheme eligibility recalculate instantly.": "योजना पात्रता तुरंत देखने के लिए वित्तीय पैरामीटर समायोजित करें।",
    "run real-time scheme compatibility": "रीयल-टाइम योजना संगतता जांचें",
    "evaluating...": "मूल्यांकन जारी है...",
    "shap-style factor attribution & rule compliance": "कारक व्याख्या एवं नियम अनुपालन",
    "positive contributing factors (+ impact)": "सकारात्मक योगदान कारक (+ प्रभाव)",
    "limiting / disqualifying factors (- impact)": "सीमित करने वाले / अयोग्य कारक (- प्रभाव)",
    "ready to proceed with application?": "आवेदन प्रक्रिया आगे बढ़ाने के लिए तैयार हैं?",
    "calculate exact monthly emis after 35% subsidy or locate your nearest nodal bank.": "35% सब्सिडी के बाद अपनी सटीक ईएमआई की गणना करें या बैंक खोजें।",
    "back to matching results": "योजना परिणामों पर वापस जाएं",
    "back to scheme results": "योजना परिणामों पर वापस जाएं",
    "official portal": "आधिकारिक पोर्टल",
    "loading statutory gazette scheme details from myscheme.gov.in records...": "myScheme.gov.in रिकॉर्ड से विवरण लोड हो रहा है...",
    "monthly emi": "मासिक ईएमआई (EMI)",
    "total interest payable": "कुल देय ब्याज",
    "total amount payable": "कुल देय राशि",
    "capital subsidy amount": "पूंजीगत सब्सिडी राशि",
    "net loan principal after subsidy": "सब्सिडी पश्चात शुद्ध मूलधन",
    "moratorium period": "अधिस्थगन अवधि (मोराटोरियम)",
    "loan quantum (₹)": "ऋण राशि (₹)",
    "tenure (years)": "अवधि (वर्ष)",
    "annual interest rate (%)": "वार्षिक ब्याज दर (%)",
    "applicable subsidy (%)": "लागू सब्सिडी (%)",
    "moratorium / grace period (months)": "अधिस्थगन अवधि (महीने)",
    "emi & capital subsidy calculator": "ईएमआई एवं पूंजीगत सब्सिडी कैलकुलेटर",
    "amortization schedule": "मासिक ऋण भुगतान अनुसूची",
    "month": "महीना",
    "principal paid": "मूलधन भुगतान",
    "interest paid": "ब्याज भुगतान",
    "remaining balance": "शेष ऋण राशि",
    "print emi summary": "ईएमआई सारांश प्रिंट करें",
    "document vault (indexed)": "दस्तावेज़ वॉल्ट (सत्यापित)",
    "upload file (ocr)": "फ़ाइल अपलोड करें (OCR)",
    "1-click synthetic samples": "1-क्लिक नमूना दस्तावेज़",
    "direct text stream": "प्रत्यक्ष टेक्स्ट सत्यापन",
    "multilingual ocr document assistant": "बहुभाषी ओसीआर दस्तावेज़ सहायक",
    "auto-extract, pre-validate & hash documents": "दस्तावेज़ों से डेटा निकालें और सत्यापित करें",
    "verified": "सत्यापित",
    "pending": "लंबित",
    "optional": "वैकल्पिक",
    "mandatory": "अनिवार्य",
    "document audit logs": "दस्तावेज़ ऑडिट लॉग"
  },
  te: {
    "find my scheme": "పథకాన్ని కనుగొనండి",
    "step 1: choose your primary focus / objective": "దశ 1: మీ ప్రాథమిక లక్ష్యాన్ని ఎంచుకోండి",
    "education & student loans": "విద్య & విద్యార్థి రుణాలు",
    "business & enterprise setup": "వ్యాపారం & పరిశ్రమల స్థాపన",
    "self-employment & artisans": "స్వయం ఉపాధి & చేతివృత్తులు",
    "eligible schemes": "అర్హతగల పథకాలు",
    "max potential subsidy": "గరిష్ట సంభావ్య సబ్సిడీ",
    "application readiness": "దరఖాస్తు సంసిద్ధత",
    "partner banks near you": "సమీప బ్యాంక్ శాఖలు",
    "100% rule verified": "100% నిబంధనల ప్రకారం ధృవీకరించబడింది",
    "previous": "మునుపటి దశ",
    "next step": "తదుపరి దశ",
    "confirm & save profile": "ప్రొఫైల్‌ను నిర్ధారించండి",
    "confirm & proceed to document assistant": "ధృవీకరించి పత్రాల సహాయకుడికి వెళ్లండి",
    "full name": "పూర్తి పేరు",
    "age (years)": "వయస్సు (సంవత్సరాలు)",
    "gender": "లింగం",
    "1. profile": "1. ప్రొఫైల్",
    "2. requirement": "2. అవసరాలు",
    "3. documents": "3. పత్రాలు",
    "4. eligibility": "4. అర్హత",
    "5. scheme": "5. పథకం",
    "6. emi": "6. EMI",
    "7. partner map": "7. భాగస్వామ్య మ్యాప్",
    "dashboard overview": "డ్యాష్‌బోర్డ్ అవలోకనం",
    "requirement questionnaire": "అవసరాల ప్రశ్నాపత్రం",
    "recommended schemes": "సిఫార్సు చేయబడిన పథకాలు",
    "financial / emi calculator": "ఈఎంఐ కాలిక్యులేటర్",
    "document assistant (ocr)": "పత్రాల సహాయకుడు (OCR)",
    "document checklist": "పత్రాల చెక్‌లిస్ట్",
    "channel partner locator": "బ్యాంకు శాఖల గుర్తింపు",
    "scheme sathi ai chat": "ఏఐ చాట్ సహాయకుడు",
    "saved schemes & history": "సేవ్ చేసిన పథకాలు & చరిత్ర",
    "notifications": "నోటిఫికేషన్‌లు",
    "my profile": "నా ప్రొఫైల్",
    "sign out": "లాగ్ అవుట్"
  }
};

// Copy Hindi phrase map to other Indic languages if not explicitly defined
['kn', 'ml', 'mr', 'bn', 'gu', 'pa', 'or', 'as'].forEach(code => {
  if (!PHRASE_MAP[code]) {
    PHRASE_MAP[code] = { ...PHRASE_MAP.hi };
  }
});

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(
    localStorage.getItem('scheme_sathi_lang') || 'en'
  );

  const setLanguage = (langCode) => {
    localStorage.setItem('scheme_sathi_lang', langCode);
    setCurrentLanguage(langCode);
  };

  const t = (keyOrPhrase, fallback) => {
    if (!keyOrPhrase) return '';
    const textStr = String(keyOrPhrase).trim();
    if (currentLanguage === 'en') return fallback !== undefined ? fallback : textStr;

    // 1. Direct dictionary key match
    const langDict = DICTIONARY[currentLanguage];
    if (langDict && langDict[textStr]) {
      return langDict[textStr];
    }

    // 2. Direct phrase map match (case-insensitive)
    const phraseMap = PHRASE_MAP[currentLanguage];
    const lowerKey = textStr.toLowerCase();
    if (phraseMap && phraseMap[lowerKey]) {
      return phraseMap[lowerKey];
    }

    // 3. Fallback to Hindi phrase map if available
    if (PHRASE_MAP.hi && PHRASE_MAP.hi[lowerKey] && currentLanguage !== 'en') {
      return PHRASE_MAP.hi[lowerKey];
    }

    // 4. Default fallback
    return fallback !== undefined ? fallback : textStr;
  };

  const translateScheme = (scheme) => {
    if (!scheme || currentLanguage === 'en') return scheme;
    const code = scheme.code || scheme.scheme_code || '';
    const localized = SCHEME_MAP[code]?.[currentLanguage] || SCHEME_MAP[code]?.hi;
    if (localized) {
      return {
        ...scheme,
        name: localized.name || scheme.name,
        scheme_name: localized.name || scheme.scheme_name,
        description: localized.desc || scheme.description,
        scheme_description: localized.desc || scheme.scheme_description
      };
    }
    return scheme;
  };

  const translateDynamic = async (text) => {
    if (!text || currentLanguage === 'en') return text;
    try {
      const res = await axios.post('/api/v1/translate', {
        text: text,
        target_language: currentLanguage
      });
      return res.data.translated_text || text;
    } catch (e) {
      return text;
    }
  };

  return (
    <LanguageContext.Provider value={{
      currentLanguage,
      language: currentLanguage,
      setLanguage, 
      t, 
      translateScheme,
      translateDynamic,
      languages: LANGUAGES
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
